// examples/angular-app/src/app/pages/back-to-top.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-back-to-top',
  standalone: true,
  templateUrl: './back-to-top.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class BackToTopComponent {}

<h1>Back to top</h1>

<section style="height: 2000px; background: linear-gradient(white, lightgray); margin-top: 20px;">
  <p>Scrolla la pagina per vedere il pulsante "Torna su" apparire nell'angolo in basso a destra.</p>
  <p class="small">
    Il componente è stato inserito nel file footer.component.ts per fare in modo che la sua posizione nel DOM sia dopo il footer.
    In questo modo è anche presente in tutte le pagine dell'applicazione di esempio.
  </p>
</section>

// examples/vue-app/src/components/BackToTop.vue
<script setup>
</script>

<template>
  <h1>Back to top</h1>
  <section style="height: 2000px; background: linear-gradient(white, lightgray); margin-top: 20px;">
    <p>Scrolla la pagina per vedere il pulsante "Torna su" apparire nell'angolo in basso a destra.</p>
    <p class="small">Il componente è stato inserito nel file App.vue per fare in modo che la sua posizione nel DOM sia dopo il footer. In questo modo è anche presente in tutte le pagine dell'applicazione di esempio. </p>
  </section>
</template>
