// examples/svelte-app/src/components/Footer.svelte
<footer class="it-footer">
  <div class="it-footer-main">
    <div class="container">
      <section class="pb-4">
        <div class="row clearfix">
          <div class="col-sm-12">
            <div class="it-brand-wrapper">
              <a href="#">
                <it-icon name="it-pa" size="lg" color="white"></it-icon>
                <div class="it-brand-text ms-3">
                  <h2 class="no_toc">Nome Ente</h2>
                  <h3 class="no_toc">Tagline</h3>
                </div>
              </a>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
            <h4>
              <a href="#" title="Vai alla pagina: Amministrazione">Amministrazione</a>
            </h4>
            <div class="link-list-wrapper">
              <ul class="footer-list link-list clearfix">
                <li><a class="list-item" href="#">Giunta e consiglio</a></li>
                <li><a class="list-item" href="#">Aree di competenza</a></li>
                <li><a class="list-item" href="#">Dipendenti</a></li>
                <li><a class="list-item" href="#">Luoghi</a></li>
                <li><a class="list-item" href="#">Associazioni e società partecipate</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
            <h4>
              <a href="#" title="Vai alla pagina: Servizi">Servizi</a>
            </h4>
            <div class="link-list-wrapper">
              <ul class="footer-list link-list clearfix">
                <li><a class="list-item" href="#">Pagamenti</a></li>
                <li><a class="list-item" href="#">Sostegno</a></li>
                <li><a class="list-item" href="#">Domande e iscrizioni</a></li>
                <li><a class="list-item" href="#">Segnalazioni</a></li>
                <li><a class="list-item" href="#">Autorizzazioni e concessioni</a></li>
                <li><a class="list-item" href="#">Certificati e dichiarazioni</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
            <h4>
              <a href="#" title="Vai alla pagina: Novità">Novità</a>
            </h4>
            <div class="link-list-wrapper">
              <ul class="footer-list link-list clearfix">
                <li><a class="list-item" href="#">Notizie</a></li>
                <li><a class="list-item" href="#">Eventi</a></li>
                <li><a class="list-item" href="#">Comunicati stampa</a></li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-3 col-sm-6">
            <h4>
              <a href="#" title="Vai alla pagina: Documenti">Documenti</a>
            </h4>
            <div class="link-list-wrapper">
              <ul class="footer-list link-list clearfix">
                <li><a class="list-item" href="#">Progetti e attività</a></li>
                <li><a class="list-item" href="#">Delibere, determine e ordinanze</a></li>
                <li><a class="list-item" href="#">Bandi</a></li>
                <li><a class="list-item" href="#">Concorsi</a></li>
                <li><a class="list-item" href="#">Albo pretorio</a></li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section class="py-4 border-white border-top">
        <div class="row">
          <div class="col-lg-4 col-md-4 pb-2">
            <h4>Contatti</h4>
            <p>
              <strong>Nome Ente</strong><br />
              Via Roma 0 - 00000 Città - Codice fiscale / P. IVA: 000000000
            </p>
            <div class="link-list-wrapper">
              <ul class="footer-list link-list clearfix">
                <li><a class="list-item" href="#">Posta Elettronica Certificata</a></li>
                <li>
                  <a class="list-item" href="#">URP - Ufficio Relazioni con il Pubblico</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 pb-2">
            <div class="pb-2">
              <h4>Seguici su</h4>
              <ul class="list-inline text-left social">
                <li class="list-inline-item">
                  <a class="p-2 text-white" href="#">
                    <it-icon color="white" size="sm" name="it-designers-italia"></it-icon>
                    <span class="visually-hidden">Designers Italia (link esterno)</span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="p-2 text-white" href="#">
                    <it-icon color="white" size="sm" name="it-twitter"></it-icon>
                    <span class="visually-hidden">X (link esterno)</span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="p-2 text-white" href="#">
                    <it-icon color="white" size="sm" name="it-medium"></it-icon>
                    <span class="visually-hidden">Medium (link esterno)</span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a class="p-2 text-white" href="#">
                    <it-icon color="white" size="sm" name="it-behance"></it-icon>
                    <span class="visually-hidden">Behance (link esterno)</span>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 mt-2">
            <h4>Newsletter</h4>
            <div class="form-group d-flex gap-1">
              <it-input
                slotted
                type="text"
                id="newsletter-email"
                size="sm"
                placeholder="Inserisci la tua email"
                label-hidden
              >
                <it-button type="submit" variant="primary" slot="append">Iscriviti</it-button>
              </it-input>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
  <div class="it-footer-small-prints clearfix">
    <div class="container">
      <ul class="it-footer-small-prints-list list-inline mb-0 d-flex flex-column flex-md-row">
        <li class="list-inline-item"><a href="#">Media policy</a></li>
        <li class="list-inline-item"><a href="#">Note legali</a></li>
        <li class="list-inline-item"><a href="#">Privacy policy</a></li>
        <li class="list-inline-item"><a href="#">Mappa del sito</a></li>
        <li class="list-inline-item">
          <a href="https://form.agid.gov.it/view/xyz">
            Dichiarazione di accessibilità <span class="visually-hidden">(link esterno su sito AgID)</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>

// examples/vue-app/src/components/Footer.vue
<template>
  <footer class="it-footer">
    <div class="it-footer-main">
      <div class="container">
        <section class="pb-4">
          <div class="row clearfix">
            <div class="col-sm-12">
              <div class="it-brand-wrapper">
                <a href="#">
                  <it-icon name="it-pa" size="lg" color="white"></it-icon>
                  <div class="it-brand-text ms-3">
                    <h2 class="no_toc">Nome Ente</h2>
                    <h3 class="no_toc">Tagline</h3>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
              <h4>
                <a href="#" title="Vai alla pagina: Amministrazione">Amministrazione</a>
              </h4>
              <div class="link-list-wrapper">
                <ul class="footer-list link-list clearfix">
                  <li><a class="list-item" href="#">Giunta e consiglio</a></li>
                  <li><a class="list-item" href="#">Aree di competenza</a></li>
                  <li><a class="list-item" href="#">Dipendenti</a></li>
                  <li><a class="list-item" href="#">Luoghi</a></li>
                  <li><a class="list-item" href="#">Associazioni e società partecipate</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
              <h4>
                <a href="#" title="Vai alla pagina: Servizi">Servizi</a>
              </h4>
              <div class="link-list-wrapper">
                <ul class="footer-list link-list clearfix">
                  <li><a class="list-item" href="#">Pagamenti</a></li>
                  <li><a class="list-item" href="#">Sostegno</a></li>
                  <li><a class="list-item" href="#">Domande e iscrizioni</a></li>
                  <li><a class="list-item" href="#">Segnalazioni</a></li>
                  <li><a class="list-item" href="#">Autorizzazioni e concessioni</a></li>
                  <li><a class="list-item" href="#">Certificati e dichiarazioni</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 pb-2">
              <h4>
                <a href="#" title="Vai alla pagina: Novità">Novità</a>
              </h4>
              <div class="link-list-wrapper">
                <ul class="footer-list link-list clearfix">
                  <li><a class="list-item" href="#">Notizie</a></li>
                  <li><a class="list-item" href="#">Eventi</a></li>
                  <li><a class="list-item" href="#">Comunicati stampa</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
              <h4>
                <a href="#" title="Vai alla pagina: Documenti">Documenti</a>
              </h4>
              <div class="link-list-wrapper">
                <ul class="footer-list link-list clearfix">
                  <li><a class="list-item" href="#">Progetti e attività</a></li>
                  <li><a class="list-item" href="#">Delibere, determine e ordinanze</a></li>
                  <li><a class="list-item" href="#">Bandi</a></li>
                  <li><a class="list-item" href="#">Concorsi</a></li>
                  <li><a class="list-item" href="#">Albo pretorio</a></li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section class="py-4 border-white border-top">
          <div class="row">
            <div class="col-lg-4 col-md-4 pb-2">
              <h4>Contatti</h4>
              <p>
                <strong>Nome Ente</strong><br />
                Via Roma 0 - 00000 Città - Codice fiscale / P. IVA: 000000000
              </p>
              <div class="link-list-wrapper">
                <ul class="footer-list link-list clearfix">
                  <li><a class="list-item" href="#">Posta Elettronica Certificata</a></li>
                  <li>
                    <a class="list-item" href="#">URP - Ufficio Relazioni con il Pubblico</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-lg-4 col-md-4 pb-2">
              <div class="pb-2">
                <h4>Seguici su</h4>
                <ul class="list-inline text-left social">
                  <li class="list-inline-item">
                    <a class="p-2 text-white" href="#">
                      <it-icon color="white" size="sm" name="it-designers-italia"></it-icon>
                      <span class="visually-hidden">Designers Italia (link esterno)</span>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a class="p-2 text-white" href="#">
                      <it-icon color="white" size="sm" name="it-twitter"></it-icon>
                      <span class="visually-hidden">X (link esterno)</span>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a class="p-2 text-white" href="#">
                      <it-icon color="white" size="sm" name="it-medium"></it-icon>
                      <span class="visually-hidden">Medium (link esterno)</span>
                    </a>
                  </li>
                  <li class="list-inline-item">
                    <a class="p-2 text-white" href="#">
                      <it-icon color="white" size="sm" name="it-behance"></it-icon>
                      <span class="visually-hidden">Behance (link esterno)</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-lg-4 col-md-4 mt-2">
              <h4>Newsletter</h4>
              <div class="form-group d-flex gap-1">
                <it-input
                  slotted
                  type="text"
                  id="newsletter-email"
                  size="sm"
                  placeholder="Inserisci la tua email"
                  label-hidden
                >
                  <span slot="label">Iscriviti alla newsletter</span>
                  <it-button type="submit" variant="primary" slot="append">Iscriviti</it-button>
                </it-input>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
    <div class="it-footer-small-prints clearfix">
      <div class="container">
        <ul class="it-footer-small-prints-list list-inline mb-0 d-flex flex-column flex-md-row">
          <li class="list-inline-item"><a href="#">Media policy</a></li>
          <li class="list-inline-item"><a href="#">Note legali</a></li>
          <li class="list-inline-item"><a href="#">Privacy policy</a></li>
          <li class="list-inline-item"><a href="#">Mappa del sito</a></li>
          <li class="list-inline-item">
            <a href="https://form.agid.gov.it/view/xyz">
              Dichiarazione di accessibilità <span class="visually-hidden">(link esterno su sito AgID)</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </footer>
</template>

<script setup>
</script>
