// examples/svelte-app/src/pages/Autocomplete.svelte
<script>

  const italianRegions = [
    { value: 'abruzzo', label: 'Abruzzo' },
    { value: 'basilicata', label: 'Basilicata' },
    { value: 'calabria', label: 'Calabria' },
    { value: 'campania', label: 'Campania' },
    { value: 'emilia-romagna', label: 'Emilia Romagna' },
    { value: 'friuli-venezia-giulia', label: 'Friuli Venezia Giulia' },
    { value: 'lazio', label: 'Lazio' },
    { value: 'liguria', label: 'Liguria' },
    { value: 'lombardia', label: 'Lombardia' },
    { value: 'marche', label: 'Marche' },
    { value: 'molise', label: 'Molise' },
    { value: 'piemonte', label: 'Piemonte' },
    { value: 'puglia', label: 'Puglia' },
    { value: 'sardegna', label: 'Sardegna' },
    { value: 'sicilia', label: 'Sicilia' },
    { value: 'toscana', label: 'Toscana' },
    { value: 'trentino-alto-adige', label: 'Trentino Alto Adige' },
    { value: 'umbria', label: 'Umbria' },
    { value: 'valle-d-aosta', label: "Valle d'Aosta" },
    { value: 'veneto', label: 'Veneto' },
  ];

  const provinces = [
    { value: 'milano', label: 'Milano' },
    { value: 'roma', label: 'Roma' },
    { value: 'napoli', label: 'Napoli' },
    { value: 'torino', label: 'Torino' },
    { value: 'palermo', label: 'Palermo' },
    { value: 'genova', label: 'Genova' },
    { value: 'bologna', label: 'Bologna' },
    { value: 'firenze', label: 'Firenze' },
    { value: 'bari', label: 'Bari' },
    { value: 'catania', label: 'Catania' },
  ];

  const cities = [
    { value: 'milano', label: 'Milano' },
    { value: 'roma', label: 'Roma' },
    { value: 'napoli', label: 'Napoli' },
    { value: 'torino', label: 'Torino' },
    { value: 'palermo', label: 'Palermo' },
    { value: 'genova', label: 'Genova' },
    { value: 'bologna', label: 'Bologna' },
    { value: 'firenze', label: 'Firenze' },
    { value: 'bari', label: 'Bari' },
    { value: 'catania', label: 'Catania' },
    { value: 'venezia', label: 'Venezia' },
    { value: 'verona', label: 'Verona' },
    { value: 'messina', label: 'Messina' },
    { value: 'padova', label: 'Padova' },
    { value: 'trieste', label: 'Trieste' },
    { value: 'brescia', label: 'Brescia' },
    { value: 'parma', label: 'Parma' },
    { value: 'taranto', label: 'Taranto' },
    { value: 'prato', label: 'Prato' },
    { value: 'modena', label: 'Modena' },
    { value: 'reggio-calabria', label: 'Reggio Calabria' },
    { value: 'reggio-emilia', label: 'Reggio Emilia' },
    { value: 'perugia', label: 'Perugia' },
    { value: 'ravenna', label: 'Ravenna' },
    { value: 'livorno', label: 'Livorno' },
    { value: 'cagliari', label: 'Cagliari' },
    { value: 'foggia', label: 'Foggia' },
  ];

  const categories = {
    frutta: [
      { value: 'mela', label: 'Mela' },
      { value: 'pera', label: 'Pera' },
      { value: 'banana', label: 'Banana' },
      { value: 'arancia', label: 'Arancia' },
      { value: 'fragola', label: 'Fragola' },
      { value: 'kiwi', label: 'Kiwi' },
      { value: 'ananas', label: 'Ananas' },
      { value: 'mango', label: 'Mango' },
      { value: 'pesca', label: 'Pesca' },
      { value: 'albicocca', label: 'Albicocca' },
      { value: 'ciliegia', label: 'Ciliegia' },
      { value: 'uva', label: 'Uva' },
      { value: 'melone', label: 'Melone' },
      { value: 'anguria', label: 'Anguria' },
      { value: 'pompelmo', label: 'Pompelmo' },
      { value: 'mandarino', label: 'Mandarino' },
      { value: 'limone', label: 'Limone' },
      { value: 'prugna', label: 'Prugna' },
      { value: 'fico', label: 'Fico' },
      { value: 'melograno', label: 'Melograno' },
    ],
    verdura: [
      { value: 'carota', label: 'Carota' },
      { value: 'pomodoro', label: 'Pomodoro' },
      { value: 'lattuga', label: 'Lattuga' },
      { value: 'zucchina', label: 'Zucchina' },
      { value: 'melanzana', label: 'Melanzana' },
      { value: 'peperone', label: 'Peperone' },
      { value: 'cipolla', label: 'Cipolla' },
      { value: 'aglio', label: 'Aglio' },
      { value: 'patata', label: 'Patata' },
      { value: 'spinaci', label: 'Spinaci' },
      { value: 'broccoli', label: 'Broccoli' },
      { value: 'cavolfiore', label: 'Cavolfiore' },
      { value: 'cavolo', label: 'Cavolo' },
      { value: 'sedano', label: 'Sedano' },
      { value: 'finocchio', label: 'Finocchio' },
      { value: 'cetriolo', label: 'Cetriolo' },
      { value: 'ravanello', label: 'Ravanello' },
      { value: 'rucola', label: 'Rucola' },
      { value: 'valeriana', label: 'Valeriana' },
      { value: 'barbabietola', label: 'Barbabietola' },
    ],
    cereali: [
      { value: 'riso', label: 'Riso' },
      { value: 'pasta', label: 'Pasta' },
      { value: 'pane', label: 'Pane' },
      { value: 'farro', label: 'Farro' },
      { value: 'orzo', label: 'Orzo' },
      { value: 'quinoa', label: 'Quinoa' },
      { value: 'avena', label: 'Avena' },
      { value: 'miglio', label: 'Miglio' },
      { value: 'grano-saraceno', label: 'Grano saraceno' },
      { value: 'segale', label: 'Segale' },
      { value: 'couscous', label: 'Couscous' },
      { value: 'bulgur', label: 'Bulgur' },
      { value: 'amaranto', label: 'Amaranto' },
      { value: 'mais', label: 'Mais' },
      { value: 'kamut', label: 'Kamut' },
    ],
    legumi: [
      { value: 'fagioli', label: 'Fagioli' },
      { value: 'lenticchie', label: 'Lenticchie' },
      { value: 'ceci', label: 'Ceci' },
      { value: 'piselli', label: 'Piselli' },
      { value: 'fave', label: 'Fave' },
      { value: 'soia', label: 'Soia' },
      { value: 'lupini', label: 'Lupini' },
      { value: 'fagioli-borlotti', label: 'Fagioli borlotti' },
      { value: 'fagioli-cannellini', label: 'Fagioli cannellini' },
      { value: 'fagioli-neri', label: 'Fagioli neri' },
      { value: 'cicerchie', label: 'Cicerchie' },
      { value: 'fagiolini', label: 'Fagiolini' },
    ],
    latticini: [
      { value: 'latte', label: 'Latte' },
      { value: 'yogurt', label: 'Yogurt' },
      { value: 'mozzarella', label: 'Mozzarella' },
      { value: 'parmigiano', label: 'Parmigiano' },
      { value: 'pecorino', label: 'Pecorino' },
      { value: 'gorgonzola', label: 'Gorgonzola' },
      { value: 'ricotta', label: 'Ricotta' },
      { value: 'burro', label: 'Burro' },
      { value: 'formaggio-spalmabile', label: 'Formaggio spalmabile' },
      { value: 'mascarpone', label: 'Mascarpone' },
      { value: 'fontina', label: 'Fontina' },
      { value: 'taleggio', label: 'Taleggio' },
      { value: 'grana-padano', label: 'Grana Padano' },
      { value: 'caciocavallo', label: 'Caciocavallo' },
    ],
  };

  let formOutput = '';
  let selectedCategory = 'frutta';

  // Funzione Source Asincrona
  const asyncSearchFunction = (query, populateResults) => {
    setTimeout(() => {
      const lowerQuery = query.toLowerCase();
      const results = cities.filter((city) => city.label.toLowerCase().includes(lowerQuery)).slice(0, 10);
      populateResults(results);
    }, 800);
  };

  function handleFormSubmit(e) {
    e.preventDefault();
    const formData = new FormData(e.target);
    const data = {};
    formData.forEach((value, key) => {
      data[key] = value;
    });
    formOutput = JSON.stringify(data, null, 2);
  }
</script>

<div class="container my-4">
  <h1>Autocomplete</h1>
  <p class="lead">Esempi di utilizzo del componente autocomplete con Svelte</p>

  <section class="example-section">
    <h2>Esempio di autocompletamento</h2>
    <p>Autocomplete base con regioni italiane</p>
    <div class="form-group">
      <it-autocomplete name="regione" placeholder="Seleziona una regione..." source={italianRegions}>
        <span slot="label">Regione</span>
      </it-autocomplete>
    </div>
  </section>

  <section class="example-section">
    <h2>Con placeholder</h2>
    <p>Campo con testo segnaposto</p>
    <it-autocomplete name="regione" placeholder="Es: Lombardia" source={italianRegions}>
      <span slot="label">Cerca regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Campo obbligatorio</h2>
    <p>Campo con validazione required</p>
    <form on:submit|preventDefault={() => {}}>
      <it-autocomplete name="regione" required source={italianRegions}>
        <span slot="label">Regione</span>
      </it-autocomplete>
      <it-button type="submit" variant="primary" class="mt-3">Valida</it-button>
    </form>
  </section>

  <section class="example-section">
    <h2>Con lunghezza minima</h2>
    <p>Mostra suggerimenti solo dopo 3 caratteri</p>
    <it-autocomplete name="regione" min-length="3" source={italianRegions}>
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Campo disabilitato</h2>
    <p>Campo non modificabile</p>
    <it-autocomplete name="regione" disabled default-value="lombardia" source={italianRegions}>
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Etichetta nascosta</h2>
    <p>Label accessibile ma visivamente nascosta</p>
    <it-autocomplete name="regione" label-hidden placeholder="Cerca regione..." source={italianRegions}>
      <span slot="label">Cerca regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Valore predefinito (stringa)</h2>
    <p>Autocomplete con valore predefinito come stringa</p>
    <it-autocomplete name="regione-default" default-value="lombardia" source={italianRegions}>
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Valore predefinito (oggetto)</h2>
    <p>Autocomplete con valore predefinito come oggetto (utile per source asincrone)</p>
    <it-autocomplete
      name="regione-default-obj"
      defaultValue={{ value: 'lazio', label: 'Lazio' }}
      source={italianRegions}
    >
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Ricerca asincrona</h2>
    <p>Usa una funzione per ricerche asincrone (API, database, ecc.)</p>
    <it-autocomplete name="citta" min-length="2" source={asyncSearchFunction}>
      <span slot="label">Cerca città</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Cambiare i valori dinamicamente</h2>
    <p>L'autocomplete si aggiorna in base alla categoria selezionata</p>
    <div class="row">
      <div class="col-12 col-md-6 mb-3">
        <div class="form-group">
          <label for="categoria-select">Categoria alimento</label>
          <select id="categoria-select" class="form-control" bind:value={selectedCategory}>
            <option value="frutta">Frutta</option>
            <option value="verdura">Verdura</option>
            <option value="cereali">Cereali</option>
            <option value="legumi">Legumi</option>
            <option value="latticini">Latticini</option>
          </select>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <it-autocomplete key={selectedCategory} name="alimento" source={categories[selectedCategory]}>
          <span slot="label">Alimento</span>
        </it-autocomplete>
      </div>
    </div>
  </section>

  <section class="example-section">
    <h2>Integrazione con form</h2>
    <p>Validazione nativa del browser e gestione FormData</p>
    <form on:submit|preventDefault={handleFormSubmit}>
      <div class="row">
        <div class="col-12 col-md-6 mb-3">
          <it-autocomplete name="regione" required source={italianRegions}>
            <span slot="label">Regione</span>
          </it-autocomplete>
        </div>
        <div class="col-12 col-md-6 mb-3">
          <it-autocomplete name="provincia" source={provinces}>
            <span slot="label">Provincia</span>
          </it-autocomplete>
        </div>
      </div>
      <it-button type="submit" variant="primary">Invia</it-button>

    </form>
  </section>
</div>

// examples/angular-app/src/app/pages/autocomplete.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-autocomplete',
  standalone: true,
  imports: [CommonModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './autocomplete.component.html',
})
export class AutocompleteComponent implements AfterViewInit {
  // Riferimenti al DOM
  @ViewChild('autoBase') autoBase!: ElementRef;

  @ViewChild('autoPlaceholder') autoPlaceholder!: ElementRef;

  @ViewChild('autoRequired') autoRequired!: ElementRef;

  @ViewChild('autoMinlength') autoMinlength!: ElementRef;

  @ViewChild('autoDisabled') autoDisabled!: ElementRef;

  @ViewChild('autoHiddenLabel') autoHiddenLabel!: ElementRef;

  @ViewChild('autoDefaultStr') autoDefaultStr!: ElementRef;

  @ViewChild('autoDefaultObj') autoDefaultObj!: ElementRef;

  @ViewChild('autoAsync') autoAsync!: ElementRef;

  @ViewChild('autoAlimento') autoAlimento!: ElementRef;

  @ViewChild('autoFormRegione') autoFormRegione!: ElementRef;

  @ViewChild('autoFormProvincia') autoFormProvincia!: ElementRef;

  formOutput = '';

  // Dati
  italianRegions = [
    { value: 'abruzzo', label: 'Abruzzo' },
    { value: 'basilicata', label: 'Basilicata' },
    { value: 'calabria', label: 'Calabria' },
    { value: 'campania', label: 'Campania' },
    { value: 'emilia-romagna', label: 'Emilia Romagna' },
    { value: 'friuli-venezia-giulia', label: 'Friuli Venezia Giulia' },
    { value: 'lazio', label: 'Lazio' },
    { value: 'liguria', label: 'Liguria' },
    { value: 'lombardia', label: 'Lombardia' },
    { value: 'marche', label: 'Marche' },
    { value: 'molise', label: 'Molise' },
    { value: 'piemonte', label: 'Piemonte' },
    { value: 'puglia', label: 'Puglia' },
    { value: 'sardegna', label: 'Sardegna' },
    { value: 'sicilia', label: 'Sicilia' },
    { value: 'toscana', label: 'Toscana' },
    { value: 'trentino-alto-adige', label: 'Trentino Alto Adige' },
    { value: 'umbria', label: 'Umbria' },
    { value: 'valle-d-aosta', label: "Valle d'Aosta" },
    { value: 'veneto', label: 'Veneto' },
  ];

  cities = [
    { value: 'milano', label: 'Milano' },
    { value: 'roma', label: 'Roma' },
    { value: 'napoli', label: 'Napoli' },
    { value: 'torino', label: 'Torino' },
    { value: 'palermo', label: 'Palermo' },
    { value: 'genova', label: 'Genova' },
    { value: 'bologna', label: 'Bologna' },
    { value: 'firenze', label: 'Firenze' },
    { value: 'bari', label: 'Bari' },
    { value: 'catania', label: 'Catania' },
    { value: 'venezia', label: 'Venezia' },
    { value: 'verona', label: 'Verona' },
    { value: 'messina', label: 'Messina' },
    { value: 'padova', label: 'Padova' },
    { value: 'trieste', label: 'Trieste' },
    { value: 'brescia', label: 'Brescia' },
    { value: 'parma', label: 'Parma' },
    { value: 'taranto', label: 'Taranto' },
    { value: 'prato', label: 'Prato' },
    { value: 'modena', label: 'Modena' },
    { value: 'reggio-calabria', label: 'Reggio Calabria' },
    { value: 'reggio-emilia', label: 'Reggio Emilia' },
    { value: 'perugia', label: 'Perugia' },
    { value: 'ravenna', label: 'Ravenna' },
    { value: 'livorno', label: 'Livorno' },
    { value: 'cagliari', label: 'Cagliari' },
    { value: 'foggia', label: 'Foggia' },
  ];

  provinces = [
    { value: 'milano', label: 'Milano' },
    { value: 'roma', label: 'Roma' },
    { value: 'napoli', label: 'Napoli' },
    { value: 'torino', label: 'Torino' },
    { value: 'palermo', label: 'Palermo' },
    { value: 'genova', label: 'Genova' },
    { value: 'bologna', label: 'Bologna' },
    { value: 'firenze', label: 'Firenze' },
    { value: 'bari', label: 'Bari' },
    { value: 'catania', label: 'Catania' },
  ];

  categories: {
    [key: string]: Array<{ value: string; label: string }>;
  } = {
    frutta: [
      { value: 'mela', label: 'Mela' },
      { value: 'pera', label: 'Pera' },
      { value: 'banana', label: 'Banana' },
      { value: 'arancia', label: 'Arancia' },
      { value: 'fragola', label: 'Fragola' },
      { value: 'kiwi', label: 'Kiwi' },
      { value: 'ananas', label: 'Ananas' },
      { value: 'mango', label: 'Mango' },
      { value: 'pesca', label: 'Pesca' },
      { value: 'albicocca', label: 'Albicocca' },
      { value: 'ciliegia', label: 'Ciliegia' },
      { value: 'uva', label: 'Uva' },
      { value: 'melone', label: 'Melone' },
      { value: 'anguria', label: 'Anguria' },
      { value: 'pompelmo', label: 'Pompelmo' },
      { value: 'mandarino', label: 'Mandarino' },
      { value: 'limone', label: 'Limone' },
      { value: 'prugna', label: 'Prugna' },
      { value: 'fico', label: 'Fico' },
      { value: 'melograno', label: 'Melograno' },
    ],
    verdura: [
      { value: 'carota', label: 'Carota' },
      { value: 'pomodoro', label: 'Pomodoro' },
      { value: 'lattuga', label: 'Lattuga' },
      { value: 'zucchina', label: 'Zucchina' },
      { value: 'melanzana', label: 'Melanzana' },
      { value: 'peperone', label: 'Peperone' },
      { value: 'cipolla', label: 'Cipolla' },
      { value: 'aglio', label: 'Aglio' },
      { value: 'patata', label: 'Patata' },
      { value: 'spinaci', label: 'Spinaci' },
      { value: 'broccoli', label: 'Broccoli' },
      { value: 'cavolfiore', label: 'Cavolfiore' },
      { value: 'cavolo', label: 'Cavolo' },
      { value: 'sedano', label: 'Sedano' },
      { value: 'finocchio', label: 'Finocchio' },
      { value: 'cetriolo', label: 'Cetriolo' },
      { value: 'ravanello', label: 'Ravanello' },
      { value: 'rucola', label: 'Rucola' },
      { value: 'valeriana', label: 'Valeriana' },
      { value: 'barbabietola', label: 'Barbabietola' },
    ],
    cereali: [
      { value: 'riso', label: 'Riso' },
      { value: 'pasta', label: 'Pasta' },
      { value: 'pane', label: 'Pane' },
      { value: 'farro', label: 'Farro' },
      { value: 'orzo', label: 'Orzo' },
      { value: 'quinoa', label: 'Quinoa' },
      { value: 'avena', label: 'Avena' },
      { value: 'miglio', label: 'Miglio' },
      { value: 'grano-saraceno', label: 'Grano saraceno' },
      { value: 'segale', label: 'Segale' },
      { value: 'couscous', label: 'Couscous' },
      { value: 'bulgur', label: 'Bulgur' },
      { value: 'amaranto', label: 'Amaranto' },
      { value: 'mais', label: 'Mais' },
      { value: 'kamut', label: 'Kamut' },
    ],
    legumi: [
      { value: 'fagioli', label: 'Fagioli' },
      { value: 'lenticchie', label: 'Lenticchie' },
      { value: 'ceci', label: 'Ceci' },
      { value: 'piselli', label: 'Piselli' },
      { value: 'fave', label: 'Fave' },
      { value: 'soia', label: 'Soia' },
      { value: 'lupini', label: 'Lupini' },
      { value: 'fagioli-borlotti', label: 'Fagioli borlotti' },
      { value: 'fagioli-cannellini', label: 'Fagioli cannellini' },
      { value: 'fagioli-neri', label: 'Fagioli neri' },
      { value: 'cicerchie', label: 'Cicerchie' },
      { value: 'fagiolini', label: 'Fagiolini' },
    ],
    latticini: [
      { value: 'latte', label: 'Latte' },
      { value: 'yogurt', label: 'Yogurt' },
      { value: 'mozzarella', label: 'Mozzarella' },
      { value: 'parmigiano', label: 'Parmigiano' },
      { value: 'pecorino', label: 'Pecorino' },
      { value: 'gorgonzola', label: 'Gorgonzola' },
      { value: 'ricotta', label: 'Ricotta' },
      { value: 'burro', label: 'Burro' },
      { value: 'formaggio-spalmabile', label: 'Formaggio spalmabile' },
      { value: 'mascarpone', label: 'Mascarpone' },
      { value: 'fontina', label: 'Fontina' },
      { value: 'taleggio', label: 'Taleggio' },
      { value: 'grana-padano', label: 'Grana Padano' },
      { value: 'caciocavallo', label: 'Caciocavallo' },
    ],
  };

  selectedCategory = 'frutta';

  ngAfterViewInit() {
    // Usiamo setTimeout per assicurarci che il custom element sia "upgradato"
    // e pronto a ricevere proprietà complesse.
    setTimeout(() => {
      this.initComponents();
    }, 0);
  }

  initComponents() {
    // 1. Base
    if (this.autoBase) {
      this.autoBase.nativeElement.source = this.italianRegions;
    }

    // 2. Placeholder
    if (this.autoPlaceholder) {
      this.autoPlaceholder.nativeElement.source = this.italianRegions;
    }

    // 3. Required
    if (this.autoRequired) {
      this.autoRequired.nativeElement.source = this.italianRegions;
    }

    // 4. MinLength
    if (this.autoMinlength) {
      this.autoMinlength.nativeElement.source = this.italianRegions;
    }

    // 5. Disabled
    if (this.autoDisabled) {
      this.autoDisabled.nativeElement.source = this.italianRegions;
      this.autoDisabled.nativeElement.value = 'lombardia';
    }

    // 6. Hidden Label
    if (this.autoHiddenLabel) {
      this.autoHiddenLabel.nativeElement.source = this.italianRegions;
    }

    // 7. Default Stringa
    if (this.autoDefaultStr) {
      this.autoDefaultStr.nativeElement.source = this.italianRegions;
      this.autoDefaultStr.nativeElement.value = 'lombardia';
    }

    // 8. Default Oggetto
    if (this.autoDefaultObj) {
      this.autoDefaultObj.nativeElement.source = this.italianRegions;
      // defaultValue è impostato come attributo nel template HTML
    }

    // 9. Async Search
    if (this.autoAsync) {
      this.autoAsync.nativeElement.source = (query: string, populateResults: any) => {
        setTimeout(() => {
          const lower = query.toLowerCase();
          const results = this.cities
            .filter((c) => c.label.toLowerCase().includes(lower))
            .slice(0, 10);
          populateResults(results);
        }, 800);
      };
    }

    // 10. Alimento (dynamic categories)
    if (this.autoAlimento) {
      this.autoAlimento.nativeElement.source = this.categories[this.selectedCategory];
    }

    // 11. Form Regione
    if (this.autoFormRegione) {
      this.autoFormRegione.nativeElement.source = this.italianRegions;
    }

    // 12. Form Provincia
    if (this.autoFormProvincia) {
      this.autoFormProvincia.nativeElement.source = this.provinces;
    }
  }

  handleRequiredSubmit(event: Event) {
    event.preventDefault();
    // alert('Form valido!');
  }

  handleFormSubmit(event: Event) {
    event.preventDefault();
    const formData = new FormData(event.target as HTMLFormElement);
    const data: any = {};
    formData.forEach((v, k) => (data[k] = v));
    this.formOutput = JSON.stringify(data, null, 2);
  }

  handleCategoryChange(event: Event) {
    const select = event.target as HTMLSelectElement;
    this.selectedCategory = select.value;
    if (this.autoAlimento) {
      this.autoAlimento.nativeElement.source = this.categories[this.selectedCategory];
      this.autoAlimento.nativeElement.value = '';
    }
  }
}

<div class="container my-4">
  <h1>Autocomplete</h1>
  <p class="lead">Esempi di utilizzo del componente autocomplete con Angular</p>

  <section class="example-section">
    <h2>Esempio di autocompletamento</h2>
    <p>Autocomplete base con regioni italiane</p>
    <div class="form-group">
      <it-autocomplete #autoBase name="regione" placeholder="Seleziona una regione...">
        <span slot="label">Regione</span>
      </it-autocomplete>
    </div>
  </section>

  <section class="example-section">
    <h2>Con placeholder</h2>
    <p>Campo con testo segnaposto</p>
    <it-autocomplete #autoPlaceholder name="regione" placeholder="Es: Lombardia">
      <span slot="label">Cerca regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Campo obbligatorio</h2>
    <p>Campo con validazione required</p>
    <form (submit)="handleRequiredSubmit($event)">
      <it-autocomplete #autoRequired name="regione" required>
        <span slot="label">Regione</span>
      </it-autocomplete>
      <it-button type="submit" variant="primary" class="mt-3">Valida</it-button>
    </form>
  </section>

  <section class="example-section">
    <h2>Con lunghezza minima</h2>
    <p>Mostra suggerimenti solo dopo 3 caratteri</p>
    <it-autocomplete #autoMinlength name="regione" min-length="3">
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Campo disabilitato</h2>
    <p>Campo non modificabile</p>
    <it-autocomplete #autoDisabled name="regione" disabled>
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Etichetta nascosta</h2>
    <p>Label accessibile ma visualmente nascosta</p>
    <it-autocomplete #autoHiddenLabel name="regione" label-hidden placeholder="Cerca regione...">
      <span slot="label">Cerca regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Valore predefinito (stringa)</h2>
    <p>Autocomplete con valore predefinito come stringa</p>
    <it-autocomplete #autoDefaultStr name="regione-default">
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Valore predefinito (oggetto)</h2>
    <p>Autocomplete con valore predefinito come oggetto (utile per source asincrone)</p>
    <it-autocomplete
      #autoDefaultObj
      name="regione-default-obj"
      default-value='{"value":"lazio","label":"Lazio"}'
    >
      <span slot="label">Regione</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Ricerca asincrona</h2>
    <p>Usa una funzione per ricerche asincrone (API, database, ecc.)</p>
    <it-autocomplete #autoAsync name="citta" min-length="2">
      <span slot="label">Cerca città</span>
    </it-autocomplete>
  </section>

  <section class="example-section">
    <h2>Cambiare i valori dinamicamente</h2>
    <p>L'autocomplete si aggiorna in base alla categoria selezionata</p>
    <div class="row">
      <div class="col-12 col-md-6 mb-3">
        <div class="form-group">
          <label for="categoria-select">Categoria alimento</label>
          <select
            id="categoria-select"
            class="form-control"
            (change)="handleCategoryChange($event)"
          >
            <option value="frutta">Frutta</option>
            <option value="verdura">Verdura</option>
            <option value="cereali">Cereali</option>
            <option value="legumi">Legumi</option>
            <option value="latticini">Latticini</option>
          </select>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <it-autocomplete #autoAlimento name="alimento">
          <span slot="label">Alimento</span>
        </it-autocomplete>
      </div>
    </div>
  </section>

  <section class="example-section">
    <h2>Integrazione con form</h2>
    <p>Validazione nativa del browser e gestione FormData</p>
    <form (submit)="handleFormSubmit($event)">
      <div class="row">
        <div class="col-12 col-md-6 mb-3">
          <it-autocomplete #autoFormRegione name="regione" required>
            <span slot="label">Regione</span>
          </it-autocomplete>
        </div>
        <div class="col-12 col-md-6 mb-3">
          <it-autocomplete #autoFormProvincia name="provincia">
            <span slot="label">Provincia</span>
          </it-autocomplete>
        </div>
      </div>
      <it-button type="submit" variant="primary">Invia</it-button>

      
    </form>
  </section>
</div>
