// examples/svelte-app/src/pages/Checkbox.svelte
<h1>it-checkbox</h1>

<it-checkbox id="chExample" label="Checkbox di esempio" name="esempio"></it-checkbox>

<section>
  <h2>Checked</h2>
  <it-checkbox id="checked" label="Checkbox di esempio selezionata" name="esempioChecked" checked></it-checkbox>
</section>

<section>
  <h2>Indeterminate</h2>
  <it-checkbox id="indeterminate" label="Checkbox di esempio indeterminata" indeterminate></it-checkbox>
</section>
<section>
  <h2>Disabilitata</h2>
  <it-checkbox id="disabledd" label="Checkbox di esempio disabilitata" disabled></it-checkbox>
</section>

<section>
  <h2>Required</h2>
  <it-checkbox id="required" label="Checkbox di esempio required" required></it-checkbox>
</section>

<section>
  <h2>Inline</h2>
  <fieldset>
    <legend>Gruppo di checkbox</legend>
    <it-checkbox id="inline-1" label="Checkbox di esempio inline 1" inline></it-checkbox>
    <it-checkbox id="inline-2" label="Checkbox di esempio inline 2" inline></it-checkbox>
  </fieldset>
</section>

<section>
  <h2>Raggruppamento</h2>
  <fieldset>
    <legend>Gruppo di checkbox</legend>
    <it-checkbox id="inline-1" label="Checkbox di esempio inline 1" group></it-checkbox>
    <it-checkbox id="inline-2" label="Checkbox di esempio inline 2" group></it-checkbox>
  </fieldset>
</section>

<section>
  <h2>Testo di supporto</h2>

  <it-checkbox id="supporttext" label="Checkbox di esempio" supportText="Testo di supporto"></it-checkbox>
</section>

<section>
  <h2>Validazione custom</h2>

  <it-checkbox
    id="customvalidation"
    label="Checkbox di esempio"
    supportText="Testo di supporto"
    custom-validation
    validity-message="Obbligatorio!"
  ></it-checkbox>
</section>

// examples/angular-app/src/app/pages/checkbox.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'checkbox-page',
  templateUrl: './checkbox.component.html',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CheckboxComponent {}

<h1>it-checkbox</h1>

<it-checkbox id="chExample" label="Checkbox di esempio" name="esempio"></it-checkbox>

<section>
  <h2>Checked</h2>
  <it-checkbox id="checked" label="Checkbox di esempio selezionata" name="esempioChecked" checked></it-checkbox>
</section>

<section>
  <h2>Indeterminate</h2>
  <it-checkbox id="indeterminate" label="Checkbox di esempio indeterminata" indeterminate></it-checkbox>
</section>
<section>
  <h2>Disabilitata</h2>
  <it-checkbox id="disabledd" label="Checkbox di esempio disabilitata" disabled></it-checkbox>
</section>

<section>
  <h2>Required</h2>
  <it-checkbox id="required" label="Checkbox di esempio required" required></it-checkbox>
</section>

<section>
  <h2>Inline</h2>
  <fieldset>
    <legend>Gruppo di checkbox</legend>
    <it-checkbox id="inline-1" label="Checkbox di esempio inline 1" inline></it-checkbox>
    <it-checkbox id="inline-2" label="Checkbox di esempio inline 2" inline></it-checkbox>
  </fieldset>
</section>

<section>
  <h2>Raggruppamento</h2>
  <fieldset>
    <legend>Gruppo di checkbox</legend>
    <it-checkbox id="inline-1" label="Checkbox di esempio inline 1" group></it-checkbox>
    <it-checkbox id="inline-2" label="Checkbox di esempio inline 2" group></it-checkbox>
  </fieldset>
</section>

<section>
  <h2>Testo di supporto</h2>

  <it-checkbox id="supporttext" label="Checkbox di esempio" supportText="Testo di supporto"></it-checkbox>
</section>

<section>
  <h2>Validazione custom</h2>

  <it-checkbox
    id="customvalidation"
    label="Checkbox di esempio"
    supportText="Testo di supporto"
    custom-validation
    validity-message="Obbligatorio!"
  ></it-checkbox>
</section>
