// examples/svelte-app/src/RadioExamples.svelte
<script>
  import { onMount } from 'svelte';
  import '@italia/radio';

  let selectedValue = 'opzione1';
  let selectedInline = 'opzione1';
  let selectedGroup = 'opzione1';

  function handleSubmit(event) {
    event.preventDefault();
    const formData = new FormData(event.target);
    const data = Object.fromEntries(formData);
    alert(`Form valido! Dati: ${JSON.stringify(data)}`);
  }
</script>

<div class="container" style="padding: 2rem">
  <h1>Esempi Radio Button - Svelte</h1>

  <!-- Esempio base -->
  <section style="margin-bottom: 3rem">
    <h2>Esempio Base</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio
        id="radio1"
        name="gruppo1"
        value="opzione1"
        checked={selectedValue === 'opzione1'}
        on:change={(e) => (selectedValue = e.target.value)}
      >
        <span slot="label">Radio di esempio 1</span>
      </it-radio>
      <it-radio
        id="radio2"
        name="gruppo1"
        value="opzione2"
        checked={selectedValue === 'opzione2'}
        on:change={(e) => (selectedValue = e.target.value)}
      >
        <span slot="label">Radio di esempio 2</span>
      </it-radio>
      <it-radio
        id="radio3"
        name="gruppo1"
        value="opzione3"
        checked={selectedValue === 'opzione3'}
        on:change={(e) => (selectedValue = e.target.value)}
      >
        <span slot="label">Radio di esempio 3</span>
      </it-radio>
    </fieldset>
    <p>Valore selezionato: <strong>{selectedValue}</strong></p>
  </section>

  <!-- Testo di supporto -->
  <section style="margin-bottom: 3rem">
    <h2>Testo di Supporto</h2>
    <fieldset>
      <legend>Gruppo di radio con testo di supporto</legend>
      <it-radio
        id="radio-support1"
        name="gruppo-support"
        value="opzione1"
        support-text="Questo è un testo di supporto per il radio button"
      >
        <span slot="label">Radio con testo di supporto</span>
      </it-radio>
      <it-radio id="radio-support2" name="gruppo-support" value="opzione2">
        <span slot="label">Altro radio</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Radio inline -->
  <section style="margin-bottom: 3rem">
    <h2>Radio Inline</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio
        id="radio-inline1"
        name="gruppo-inline"
        value="opzione1"
        inline
        checked={selectedInline === 'opzione1'}
        on:change={(e) => (selectedInline = e.target.value)}
      >
        <span slot="label">Radio inline 1</span>
      </it-radio>
      <it-radio
        id="radio-inline2"
        name="gruppo-inline"
        value="opzione2"
        inline
        checked={selectedInline === 'opzione2'}
        on:change={(e) => (selectedInline = e.target.value)}
      >
        <span slot="label">Radio inline 2</span>
      </it-radio>
      <it-radio
        id="radio-inline3"
        name="gruppo-inline"
        value="opzione3"
        inline
        checked={selectedInline === 'opzione3'}
        on:change={(e) => (selectedInline = e.target.value)}
      >
        <span slot="label">Radio inline 3</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Radio disabilitato -->
  <section style="margin-bottom: 3rem">
    <h2>Radio Disabilitato</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio id="radio-disabled1" name="gruppo-disabled" value="opzione1" checked disabled>
        <span slot="label">Radio selezionato e disabilitato</span>
      </it-radio>
      <it-radio id="radio-disabled2" name="gruppo-disabled" value="opzione2" disabled>
        <span slot="label">Radio disabilitato</span>
      </it-radio>
      <it-radio id="radio-disabled3" name="gruppo-disabled" value="opzione3">
        <span slot="label">Radio abilitato</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Raggruppati visivamente -->
  <section style="margin-bottom: 3rem">
    <h2>Raggruppati Visivamente</h2>
    <div class="row">
      <fieldset class="col-12 col-md-6">
        <legend>Gruppo di radio</legend>
        <div>
          <it-radio
            id="radio-group1"
            name="gruppo-visual"
            value="opzione1"
            group
            checked={selectedGroup === 'opzione1'}
            on:change={(e) => (selectedGroup = e.target.value)}
          >
            <span slot="label">Opzione 1</span>
          </it-radio>
          <it-radio
            id="radio-group2"
            name="gruppo-visual"
            value="opzione2"
            group
            checked={selectedGroup === 'opzione2'}
            on:change={(e) => (selectedGroup = e.target.value)}
          >
            <span slot="label">Opzione 2</span>
          </it-radio>
          <it-radio
            id="radio-group3"
            name="gruppo-visual"
            value="opzione3"
            group
            checked={selectedGroup === 'opzione3'}
            on:change={(e) => (selectedGroup = e.target.value)}
          >
            <span slot="label">Opzione 3</span>
          </it-radio>
        </div>
      </fieldset>
    </div>
  </section>

  <!-- Form con validazione -->
  <section style="margin-bottom: 3rem">
    <h2>Validazione (Required)</h2>
    <form on:submit={handleSubmit}>
      <fieldset>
        <legend>Seleziona un'opzione *</legend>
        <it-radio name="scelta-required" value="si" required>
          <span slot="label">Sì</span>
        </it-radio>
        <it-radio name="scelta-required" value="no" required>
          <span slot="label">No</span>
        </it-radio>
      </fieldset>
      <button type="submit" class="btn btn-primary mt-3">Invia</button>
    </form>
  </section>
</div>

// examples/angular-app/src/app/pages/radio-examples.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-radio-examples',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './radio-examples.component.html',
})
export class RadioExamplesComponent {
  selectedValue = 'opzione1';

  selectedInline = 'opzione1';

  selectedGroup = 'opzione1';

  handleChange(event: Event, property: 'selectedValue' | 'selectedInline' | 'selectedGroup') {
    const target = event.target as HTMLElement & { value: string };
    this[property] = target.value;
  }

  handleSubmit(event: Event) {
    event.preventDefault();
    const form = event.target as HTMLFormElement;
    const formData = new FormData(form);
    const data = Object.fromEntries(formData);
    alert(`Form valido! Dati: ${JSON.stringify(data)}`);
  }
}

<div class="container" style="padding: 2rem">
  <h1>Esempi Radio Button - Angular</h1>

  <!-- Esempio base -->
  <section style="margin-bottom: 3rem">
    <h2>Esempio Base</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio
        id="radio1"
        name="gruppo1"
        value="opzione1"
        [checked]="selectedValue === 'opzione1'"
        (change)="handleChange($event, 'selectedValue')"
      >
        <span slot="label">Radio di esempio 1</span>
      </it-radio>
      <it-radio
        id="radio2"
        name="gruppo1"
        value="opzione2"
        [checked]="selectedValue === 'opzione2'"
        (change)="handleChange($event, 'selectedValue')"
      >
        <span slot="label">Radio di esempio 2</span>
      </it-radio>
      <it-radio
        id="radio3"
        name="gruppo1"
        value="opzione3"
        [checked]="selectedValue === 'opzione3'"
        (change)="handleChange($event, 'selectedValue')"
      >
        <span slot="label">Radio di esempio 3</span>
      </it-radio>
    </fieldset>
    <p>Valore selezionato: <strong>{{ selectedValue }}</strong></p>
  </section>

  <!-- Testo di supporto -->
  <section style="margin-bottom: 3rem">
    <h2>Testo di Supporto</h2>
    <fieldset>
      <legend>Gruppo di radio con testo di supporto</legend>
      <it-radio
        id="radio-support1"
        name="gruppo-support"
        value="opzione1"
        support-text="Questo è un testo di supporto per il radio button"
      >
        <span slot="label">Radio con testo di supporto</span>
      </it-radio>
      <it-radio id="radio-support2" name="gruppo-support" value="opzione2">
        <span slot="label">Altro radio</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Radio inline -->
  <section style="margin-bottom: 3rem">
    <h2>Radio Inline</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio
        id="radio-inline1"
        name="gruppo-inline"
        value="opzione1"
        inline
        [checked]="selectedInline === 'opzione1'"
        (change)="handleChange($event, 'selectedInline')"
      >
        <span slot="label">Radio inline 1</span>
      </it-radio>
      <it-radio
        id="radio-inline2"
        name="gruppo-inline"
        value="opzione2"
        inline
        [checked]="selectedInline === 'opzione2'"
        (change)="handleChange($event, 'selectedInline')"
      >
        <span slot="label">Radio inline 2</span>
      </it-radio>
      <it-radio
        id="radio-inline3"
        name="gruppo-inline"
        value="opzione3"
        inline
        [checked]="selectedInline === 'opzione3'"
        (change)="handleChange($event, 'selectedInline')"
      >
        <span slot="label">Radio inline 3</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Radio disabilitato -->
  <section style="margin-bottom: 3rem">
    <h2>Radio Disabilitato</h2>
    <fieldset>
      <legend>Gruppo di radio</legend>
      <it-radio id="radio-disabled1" name="gruppo-disabled" value="opzione1" checked disabled>
        <span slot="label">Radio selezionato e disabilitato</span>
      </it-radio>
      <it-radio id="radio-disabled2" name="gruppo-disabled" value="opzione2" disabled>
        <span slot="label">Radio disabilitato</span>
      </it-radio>
      <it-radio id="radio-disabled3" name="gruppo-disabled" value="opzione3">
        <span slot="label">Radio abilitato</span>
      </it-radio>
    </fieldset>
  </section>

  <!-- Raggruppati visivamente -->
  <section style="margin-bottom: 3rem">
    <h2>Raggruppati Visivamente</h2>
    <div class="row">
      <fieldset class="col-12 col-md-6">
        <legend>Gruppo di radio</legend>
        <div>
          <it-radio
            id="radio-group1"
            name="gruppo-visual"
            value="opzione1"
            group
            [checked]="selectedGroup === 'opzione1'"
            (change)="handleChange($event, 'selectedGroup')"
          >
            <span slot="label">Opzione 1</span>
          </it-radio>
          <it-radio
            id="radio-group2"
            name="gruppo-visual"
            value="opzione2"
            group
            [checked]="selectedGroup === 'opzione2'"
            (change)="handleChange($event, 'selectedGroup')"
          >
            <span slot="label">Opzione 2</span>
          </it-radio>
          <it-radio
            id="radio-group3"
            name="gruppo-visual"
            value="opzione3"
            group
            [checked]="selectedGroup === 'opzione3'"
            (change)="handleChange($event, 'selectedGroup')"
          >
            <span slot="label">Opzione 3</span>
          </it-radio>
        </div>
      </fieldset>
    </div>
  </section>

  <!-- Form con validazione -->
  <section style="margin-bottom: 3rem">
    <h2>Validazione (Required)</h2>
    <form (submit)="handleSubmit($event)">
      <fieldset>
        <legend>Seleziona un'opzione *</legend>
        <it-radio name="scelta-required" value="si" required>
          <span slot="label">Sì</span>
        </it-radio>
        <it-radio name="scelta-required" value="no" required>
          <span slot="label">No</span>
        </it-radio>
      </fieldset>
      <button type="submit" class="btn btn-primary mt-3">Invia</button>
    </form>
  </section>
</div>
