// examples/svelte-app/src/pages/Transfer.svelte
<script>
  let transferStatus = '';
  let asyncStatus = '';

  function onTransfer(e) {
    if (e.detail.action === 'transfer' && e.detail.target.length > 3) {
      e.preventDefault();
      transferStatus = 'Limite di 3 elementi nel target raggiunto.';
    } else {
      transferStatus = '';
    }
  }

  function onTransferAsync(e) {
    const el = e.currentTarget;
    e.preventDefault();
    asyncStatus = 'Attendere conferma…';
    setTimeout(() => {
      el.commit(e.detail);
      asyncStatus = '';
    }, 1000);
  }
</script>

<h1>Transfer</h1>

<h2>Base</h2>
<it-transfer name="transfer-base">
  <it-transfer-item value="item1">Voce 1</it-transfer-item>
  <it-transfer-item value="item2">Voce 2</it-transfer-item>
  <it-transfer-item value="item3">Voce 3</it-transfer-item>
  <it-transfer-item value="item4">Voce 4</it-transfer-item>
  <it-transfer-item value="item5">Voce 5</it-transfer-item>
  <it-transfer-item value="item6">Voce 6</it-transfer-item>
</it-transfer>

<h2>Con valori preimpostati</h2>
<it-transfer name="transfer-preset">
  <it-transfer-item value="item7">Voce 7</it-transfer-item>
  <it-transfer-item value="item8">Voce 8</it-transfer-item>
  <it-transfer-item value="item9">Voce 9</it-transfer-item>
  <it-transfer-item value="item10" target>Voce 10</it-transfer-item>
  <it-transfer-item value="item11" target>Voce 11</it-transfer-item>
  <it-transfer-item value="item12" target>Voce 12</it-transfer-item>
</it-transfer>

<h2>Etichette personalizzate</h2>
<it-transfer
  name="transfer-labels"
  source-label="Comuni disponibili"
  target-label="Comuni selezionati"
>
  <it-transfer-item value="rm">Roma</it-transfer-item>
  <it-transfer-item value="mi">Milano</it-transfer-item>
  <it-transfer-item value="na">Napoli</it-transfer-item>
  <it-transfer-item value="to">Torino</it-transfer-item>
</it-transfer>

<h2>Con elemento non trasferibile</h2>
<it-transfer name="transfer-disabled-item">
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b" disabled>Voce B (non trasferibile)</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
</it-transfer>

<h2>Disabilitato</h2>
<it-transfer name="transfer-disabled" disabled>
  <it-transfer-item value="x">Voce X</it-transfer-item>
  <it-transfer-item value="y">Voce Y</it-transfer-item>
  <it-transfer-item value="z" target>Voce Z</it-transfer-item>
</it-transfer>

<h2>Evento cancelable: Limite di 3 elementi nel target</h2>
<it-transfer name="transfer-max-items" on:it-transfer={onTransfer}>
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b">Voce B</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
  <it-transfer-item value="d">Voce D</it-transfer-item>
  <it-transfer-item value="e">Voce E</it-transfer-item>
  <it-transfer-item value="f">Voce F</it-transfer-item>
</it-transfer>
<p role="status" aria-live="polite" style="margin-top: 1rem; color: #d32f2f;">{transferStatus}</p>

<h2>Evento cancelable con ripresa asincrona</h2>
<it-transfer name="transfer-async" on:it-transfer={onTransferAsync}>
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b">Voce B</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
  <it-transfer-item value="d">Voce D</it-transfer-item>
</it-transfer>
<p role="status" aria-live="polite" style="margin-top: 1rem;">{asyncStatus}</p>

// examples/angular-app/src/app/pages/transfer.component.ts
/* eslint-disable class-methods-use-this */
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-transfer',
  standalone: true,
  templateUrl: './transfer.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class TransferComponent {
  constructor() {}
}

<h1>Transfer</h1>

<h2>Base</h2>
<it-transfer name="transfer-base">
  <it-transfer-item value="item1">Voce 1</it-transfer-item>
  <it-transfer-item value="item2">Voce 2</it-transfer-item>
  <it-transfer-item value="item3">Voce 3</it-transfer-item>
  <it-transfer-item value="item4">Voce 4</it-transfer-item>
  <it-transfer-item value="item5">Voce 5</it-transfer-item>
  <it-transfer-item value="item6">Voce 6</it-transfer-item>
</it-transfer>

<h2>Con valori preimpostati</h2>
<it-transfer name="transfer-preset">
  <it-transfer-item value="item7">Voce 7</it-transfer-item>
  <it-transfer-item value="item8">Voce 8</it-transfer-item>
  <it-transfer-item value="item9">Voce 9</it-transfer-item>
  <it-transfer-item value="item10" target="">Voce 10</it-transfer-item>
  <it-transfer-item value="item11" target="">Voce 11</it-transfer-item>
  <it-transfer-item value="item12" target="">Voce 12</it-transfer-item>
</it-transfer>

<h2>Etichette personalizzate</h2>
<it-transfer
  name="transfer-labels"
  source-label="Comuni disponibili"
  target-label="Comuni selezionati"
>
  <it-transfer-item value="rm">Roma</it-transfer-item>
  <it-transfer-item value="mi">Milano</it-transfer-item>
  <it-transfer-item value="na">Napoli</it-transfer-item>
  <it-transfer-item value="to">Torino</it-transfer-item>
</it-transfer>

<h2>Con elemento non trasferibile</h2>
<it-transfer name="transfer-disabled-item">
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b" disabled="">Voce B (non trasferibile)</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
</it-transfer>

<h2>Disabilitato</h2>
<it-transfer name="transfer-disabled" disabled="">
  <it-transfer-item value="x">Voce X</it-transfer-item>
  <it-transfer-item value="y">Voce Y</it-transfer-item>
  <it-transfer-item value="z" target="">Voce Z</it-transfer-item>
</it-transfer>

<h2>Evento cancelable: Limite di 3 elementi nel target</h2>
<it-transfer name="transfer-max-items" #transferCancelable>
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b">Voce B</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
  <it-transfer-item value="d">Voce D</it-transfer-item>
  <it-transfer-item value="e">Voce E</it-transfer-item>
  <it-transfer-item value="f">Voce F</it-transfer-item>
</it-transfer>
<p role="status" aria-live="polite" style="margin-top: 1rem; color: #d32f2f;">{{ transferStatus }}</p>

<h2>Evento cancelable con ripresa asincrona</h2>
<it-transfer name="transfer-async" #transferAsync>
  <it-transfer-item value="a">Voce A</it-transfer-item>
  <it-transfer-item value="b">Voce B</it-transfer-item>
  <it-transfer-item value="c">Voce C</it-transfer-item>
  <it-transfer-item value="d">Voce D</it-transfer-item>
</it-transfer>
<p role="status" aria-live="polite" style="margin-top: 1rem;">{{ asyncStatus }}</p>
