// examples/angular-app/src/app/pages/navscroll.component.ts
/* eslint-disable class-methods-use-this */
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-navscroll',
  standalone: true,
  templateUrl: './navscroll.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class NavscrollComponent {
  constructor() {}
}

<h1>Navscroll</h1>

 <div class="row row-column-border border-light row-column-menu-left">
    <aside class="col-lg-4" aria-label="Indice della pagina">
      <it-navscroll breakpoint="1024" open-label="Naviga fra le sezioni" sticky="" for="#scroll-container">
        <div class="link-list-wrapper">
          <h3>Header</h3>
          <it-progress type="bar" value="0" class="it-navscroll-progressbar" aria-label="Progress bar"></it-progress>
          <nav>
            <ul class="link-list">
              <li class="nav-item">
                <a class="nav-link active" href="#p1">
                  <span>1. Introduzione </span>
                </a>
                <ul class="link-list">
                  <li class="nav-item">
                    <a class="nav-link" href="#p1_1">
                      <span>1.1 Elemento annidato </span>
                    </a>
                    <ul class="tertiary link-list">
                      <li class="nav-item">
                        <a class="nav-link" href="#p1_1_1">
                          <span>1.1.1 Elemento annidato </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#p1_1_2">
                          <span>1.1.2 Elemento annidato </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#p1_1_3">
                          <span>1.1.3 Elemento annidato </span>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#p1_2">
                      <span>1.2 Elemento annidato </span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#p1_3">
                      <span>1.3 Elemento annidato </span>
                    </a>
                  </li>
                </ul>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#p2">
                  <span>2. Seconda sezione </span>
                </a>
                <ul class="link-list">
                  <li class="nav-item">
                    <a class="nav-link" href="#p2_1">
                      <span>2.1 Elemento annidato </span>
                    </a>
                    <ul class="tertiary link-list">
                      <li class="nav-item">
                        <a class="nav-link" href="#p2_1_1">
                          <span>2.1.1 Elemento annidato </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#p2_1_2">
                          <span>2.1.2 Elemento annidato </span>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="#p2_1_3">
                          <span>2.1.3 Elemento annidato </span>
                        </a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </it-navscroll>
    </aside>

      <main id="scroll-container" class="col-lg-8 it-page-sections-container border-light">

          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec congue eros. Maecenas sagittis commodo libero
            nec porta. Nunc semper velit venenatis
            ligula condimentum ultricies. In hac habitasse platea dictumst. In malesuada pharetra nulla, id aliquam metus
            egestas ut. Nulla sollicitudin cursus
            felis, eu sagittis ante porta id. Suspendisse pellentesque ex non sem tincidunt, aliquam rhoncus turpis maximus.
            Vivamus eget massa turpis. Proin
            placerat ipsum massa, ac commodo velit tempor quis. In ante augue, sodales ac rhoncus in, ultricies a neque.
            Morbi non semper felis, at lacinia nibh.
            Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam quis
            blandit porttitor, leo erat semper sem,
            vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel
            ut quam. Cras vehicula rutrum vehicula.
            Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem euismod
            vel. Orci varius natoque penatibus et
            magnis dis parturient montes, nascetur ridiculus mus. Integer feugiat et massa nec rhoncus. Morbi vitae metus et
            sapien suscipit mattis vitae ac ex.
            Proin pharetra, sem vitae varius malesuada, risus tortor sodales arcu, eu aliquam lorem libero vel urna. Aliquam
            massa lacus, faucibus quis urna ac,
            pharetra pretium ex. In facilisis urna non urna luctus, a bibendum tortor facilisis. Mauris sed risus justo. In
            et erat fermentum eros hendrerit tempor.
            Quisque accumsan magna ac risus ultricies, vel condimentum ipsum accumsan. Proin blandit mauris sed sodales
            sollicitudin.
          </p>
          <h2 class="it-page-section" id="p1">Introduzione</h2>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue, sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h3 class="it-page-section" id="p1_1">Elemento annidato 1.1</h3>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p1_1_1">Elemento annidato 1.1.1</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p1_1_2">Elemento annidato 1.1.2</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p1_1_3">Elemento annidato 1.1.3</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h3 class="it-page-section" id="p1_2">Elemento annidato 1.2</h3>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h3 class="it-page-section" id="p1_3">Elemento annidato 1.3</h3>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h2 class="it-page-section" id="p2">Seconda sezione</h2>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h3 class="it-page-section" id="p2_1">Elemento annidato 2.1</h3>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p2_1_1">Elemento annidato 2.1.1</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p2_1_2">Elemento annidato 2.1.2</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>
          <h4 class="it-page-section" id="p2_1_3">Elemento annidato 2.1.3</h4>
          <p>
            Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a
            neque. Morbi non semper felis, at lacinia
            nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam laoreet, diam
            quis blandit porttitor, leo erat semper
            sem, vel sagittis dolor quam eu magna. Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada
            vel ut quam. Cras vehicula rutrum
            vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper
            lorem euismod vel. Orci varius natoque
            penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p>

    </main>
  </div>

// examples/svelte-app/src/pages/Navscroll.svelte
<h1>Navscroll</h1>

<div class="row row-column-border border-light row-column-menu-left">
  <aside class="col-lg-4" aria-label="Indice della pagina">
    <it-navscroll breakpoint="1024" open-label="Naviga fra le sezioni" sticky="true" for="#scroll-container">
      <div class="link-list-wrapper">
        <h3>Header</h3>
        <it-progress type="bar" value="0" class="it-navscroll-progressbar" aria-label="Progress bar"></it-progress>
        <nav>
          <ul class="link-list">
            <li class="nav-item">
              <a class="nav-link active" href="#p1">
                <span>1. Introduzione </span>
              </a>
              <ul class="link-list">
                <li class="nav-item">
                  <a class="nav-link" href="#p1_1">
                    <span>1.1 Elemento annidato </span>
                  </a>
                  <ul class="tertiary link-list">
                    <li class="nav-item">
                      <a class="nav-link" href="#p1_1_1">
                        <span>1.1.1 Elemento annidato </span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#p1_1_2">
                        <span>1.1.2 Elemento annidato </span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#p1_1_3">
                        <span>1.1.3 Elemento annidato </span>
                      </a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#p1_2">
                    <span>1.2 Elemento annidato </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#p1_3">
                    <span>1.3 Elemento annidato </span>
                  </a>
                </li>
              </ul>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#p2">
                <span>2. Seconda sezione </span>
              </a>
              <ul class="link-list">
                <li class="nav-item">
                  <a class="nav-link" href="#p2_1">
                    <span>2.1 Elemento annidato </span>
                  </a>
                  <ul class="tertiary link-list">
                    <li class="nav-item">
                      <a class="nav-link" href="#p2_1_1">
                        <span>2.1.1 Elemento annidato </span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#p2_1_2">
                        <span>2.1.2 Elemento annidato </span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#p2_1_3">
                        <span>2.1.3 Elemento annidato </span>
                      </a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </it-navscroll>
  </aside>

  <main id="scroll-container" class="col-lg-8 it-page-sections-container border-light">
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec congue eros. Maecenas sagittis commodo libero
      nec porta. Nunc semper velit venenatis ligula condimentum ultricies. In hac habitasse platea dictumst. In
      malesuada pharetra nulla, id aliquam metus egestas ut. Nulla sollicitudin cursus felis, eu sagittis ante porta id.
      Suspendisse pellentesque ex non sem tincidunt, aliquam rhoncus turpis maximus. Vivamus eget massa turpis. Proin
      placerat ipsum massa, ac commodo velit tempor quis. In ante augue, sodales ac rhoncus in, ultricies a neque. Morbi
      non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer
      feugiat et massa nec rhoncus. Morbi vitae metus et sapien suscipit mattis vitae ac ex. Proin pharetra, sem vitae
      varius malesuada, risus tortor sodales arcu, eu aliquam lorem libero vel urna. Aliquam massa lacus, faucibus quis
      urna ac, pharetra pretium ex. In facilisis urna non urna luctus, a bibendum tortor facilisis. Mauris sed risus
      justo. In et erat fermentum eros hendrerit tempor. Quisque accumsan magna ac risus ultricies, vel condimentum
      ipsum accumsan. Proin blandit mauris sed sodales sollicitudin.
    </p>
    <h2 class="it-page-section" id="p1">Introduzione</h2>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue, sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h3 class="it-page-section" id="p1_1">Elemento annidato 1.1</h3>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p1_1_1">Elemento annidato 1.1.1</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p1_1_2">Elemento annidato 1.1.2</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p1_1_3">Elemento annidato 1.1.3</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h3 class="it-page-section" id="p1_2">Elemento annidato 1.2</h3>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h3 class="it-page-section" id="p1_3">Elemento annidato 1.3</h3>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h2 class="it-page-section" id="p2">Seconda sezione</h2>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h3 class="it-page-section" id="p2_1">Elemento annidato 2.1</h3>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p2_1_1">Elemento annidato 2.1.1</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p2_1_2">Elemento annidato 2.1.2</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
    <h4 class="it-page-section" id="p2_1_3">Elemento annidato 2.1.3</h4>
    <p>
      Proin placerat ipsum massa, ac commodo velit tempor quis. In ante augue,sodales ac rhoncus in, ultricies a neque.
      Morbi non semper felis, at lacinia nibh. Nam quis elit massa. Interdum et malesuada fames ac ante ipsum primis in
      faucibus. Aliquam laoreet, diam quis blandit porttitor, leo erat semper sem, vel sagittis dolor quam eu magna.
      Nunc feugiat pretium tempor. Nam eget augue quis tellus viverra malesuada vel ut quam. Cras vehicula rutrum
      vehicula. Suspendisse efficitur eget purus vitae convallis. Integer euismod pharetra lorem, non ullamcorper lorem
      euismod vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    </p>
  </main>
</div>
