// apps/react-app/src/pages/Section.jsx
import React from 'react';

const Section = () => {
  return (
    <>
      <h1>it-section</h1>

      <it-section>
        <div className="container">
          <div className="row mb-3">
            <div className="col-12">
              <h2 id="section-heading">Morbi fermentum amet</h2>
            </div>
          </div>
          <div className="row">
            <div className="col-12 col-lg-6 col-xl-4">
              <p>
                Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Dictum sit amet justo
                donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
              </p>
            </div>
            <div className="col-12 col-lg-6 col-xl-4">
              <p>
                Eget egestas purus viverra accumsan. Diam maecenas ultricies mi eget mauris pharetra et. Etiam dignissim diam
                quis enim. Eu nisl nunc mi ipsum faucibus.
              </p>
            </div>
            <div className="col-12 col-lg-6 col-xl-4">
              <p>
                Euismod lacinia at quis risus sed vulputate. Scelerisque purus semper eget duis at tellus at urna condimentum.
                Mattis enim ut tellus elementum sagittis.
              </p>
            </div>
          </div>
        </div>
      </it-section>

      <section>
        <h2>Varianti di sfondo</h2>
        <div className="d-flex flex-column gap-4">
          <it-section variant="muted">
            <div className="container">
              <h3 id="section-heading-muted">Sezione muted</h3>
              <p>
                Questa sezione usa la variante <code>muted</code>
              </p>
            </div>
          </it-section>

          <it-section variant="emphasis" inverse>
            <div className="container">
              <h3 id="section-heading-emphasis">Sezione emphasis</h3>
              <p>
                Questa sezione usa la variante <code>emphasis</code>
                con testo bianco attraverso l'attributo inverse
              </p>
            </div>
          </it-section>

          <it-section variant="primary" inverse>
            <div className="container">
              <h3 id="section-heading-primary">Sezione primary</h3>
              <p>
                Questa sezione usa la variante <code>primary</code>
                con testo bianco attraverso l'attributo inverse
              </p>
            </div>
          </it-section>
        </div>
      </section>

      <section>
        <h2>Sezione con immagine decorativa</h2>
        <it-section image="https://picsum.photos/1280/720?image=81" inverse>
          <div className="container">
            <div className="row mb-3">
              <div className="col-12">
                <h2 id="section-heading-image">Morbi fermentum amet</h2>
              </div>
            </div>
            <div className="row">
              <div className="col-12 col-lg-6 col-xl-4">
                <p>
                  Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Dictum sit amet justo
                  donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
                </p>
              </div>
              <div className="col-12 col-lg-6 col-xl-4">
                <p>
                  Eget egestas purus viverra accumsan. Diam maecenas ultricies mi eget mauris pharetra et. Etiam dignissim diam
                  quis enim. Eu nisl nunc mi ipsum faucibus.
                </p>
              </div>
              <div className="col-12 col-lg-6 col-xl-4">
                <p>
                  Euismod lacinia at quis risus sed vulputate. Scelerisque purus semper eget duis at tellus at urna condimentum.
                  Mattis enim ut tellus elementum sagittis.
                </p>
              </div>
            </div>
          </div>
        </it-section>
      </section>

      <section>
        <h2>Sezione con card</h2>
        <it-section variant="muted">
          <div className="container">
            <div className="row">
              <div className="col">
                <h2 id="section-heading-card" className="mb-4">Morbi fermentum amet</h2>
              </div>
            </div>
            <div className="row gy-3">
              <div className="col-12 col-md-6">
                <div className="card shadow">
                  <div className="card-body">
                    <p className="card-text font-serif">
                      Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-6">
                <div className="card shadow">
                  <div className="card-body">
                    <p className="card-text font-serif">
                      Dictum sit amet justo donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </it-section>
      </section>
    </>
  );
};

export default Section;

// examples/svelte-app/src/pages/Section.svelte
<script>
</script>

<h1>it-section</h1>

<it-section>
  <div class="container">
    <div class="row mb-3">
      <div class="col-12">
        <h2 id="section-heading">Morbi fermentum amet</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-lg-6 col-xl-4">
        <p>
          Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Dictum sit amet justo
          donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
        </p>
      </div>
      <div class="col-12 col-lg-6 col-xl-4">
        <p>
          Eget egestas purus viverra accumsan. Diam maecenas ultricies mi eget mauris pharetra et. Etiam dignissim diam
          quis enim. Eu nisl nunc mi ipsum faucibus.
        </p>
      </div>
      <div class="col-12 col-lg-6 col-xl-4">
        <p>
          Euismod lacinia at quis risus sed vulputate. Scelerisque purus semper eget duis at tellus at urna condimentum.
          Mattis enim ut tellus elementum sagittis.
        </p>
      </div>
    </div>
  </div>
</it-section>

<section>
  <h2>Varianti di sfondo</h2>
  <div class="d-flex flex-column gap-4">
    <it-section variant="muted">
      <div class="container">
        <h3 id="section-heading-muted">Sezione muted</h3>
        <p>
          Questa sezione usa la variante <code>muted</code>
        </p>
      </div>
    </it-section>

    <it-section variant="emphasis" inverse>
      <div class="container">
        <h3 id="section-heading-emphasis">Sezione emphasis</h3>
        <p>
          Questa sezione usa la variante <code>emphasis</code>
          con testo bianco attraverso l'attributo inverse
        </p>
      </div>
    </it-section>

    <it-section variant="primary" inverse>
      <div class="container">
        <h3 id="section-heading-primary">Sezione primary</h3>
        <p>
          Questa sezione usa la variante <code>primary</code>
          con testo bianco attraverso l'attributo inverse
        </p>
      </div>
    </it-section>
  </div>
</section>

<section>
  <h2>Sezione con immagine decorativa</h2>
  <it-section image="https://picsum.photos/1280/720?image=81" inverse>
    <div class="container">
      <div class="row mb-3">
        <div class="col-12">
          <h2 id="section-heading-image">Morbi fermentum amet</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-lg-6 col-xl-4">
          <p>
            Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Dictum sit amet justo
            donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
          </p>
        </div>
        <div class="col-12 col-lg-6 col-xl-4">
          <p>
            Eget egestas purus viverra accumsan. Diam maecenas ultricies mi eget mauris pharetra et. Etiam dignissim diam
            quis enim. Eu nisl nunc mi ipsum faucibus.
          </p>
        </div>
        <div class="col-12 col-lg-6 col-xl-4">
          <p>
            Euismod lacinia at quis risus sed vulputate. Scelerisque purus semper eget duis at tellus at urna condimentum.
            Mattis enim ut tellus elementum sagittis.
          </p>
        </div>
      </div>
    </div>
  </it-section>
</section>

<section>
  <h2>Sezione con card</h2>
  <it-section variant="muted">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2 id="section-heading-card" class="mb-4">Morbi fermentum amet</h2>
        </div>
      </div>
      <div class="row gy-3">
        <div class="col-12 col-md-6">
          <div class="card shadow">
            <div class="card-body">
              <p class="card-text font-serif">
                Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.
              </p>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6">
          <div class="card shadow">
            <div class="card-body">
              <p class="card-text font-serif">
                Dictum sit amet justo donec enim diam vulputate ut. Eu nisl nunc mi ipsum faucibus.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </it-section>
</section>
