// examples/angular-app/src/app/pages/affix.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-affix',
  templateUrl: './affix.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  standalone: true,
})
export class AffixComponent {
  title = 'Affix';
}

<div class="container my-4">
  <h1>{{ title }}</h1>

  <!-- Affix top -->
  <section>
    <h2>Affix top</h2>
    <h3 class="h6">Esempio 1:</h3>
      <div class="affix-example container border bg-white mb-4">
        <div class="row">
          <div class="col-6 col-md-3 p-2 affix-parent">
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Lorem ipsum</p>
            </div>
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Dolor sit</p>
            </div>
            <div class="primary-bg p-3 affix-top">
              <p class="mb-0 white-color">Affix top</p>
            </div>
          </div>
          <div class="col-6 col-md-9 p-2">
            <p>
              Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur nulla
              justo, ullamcorper et pharetra nec, sagittis id augue. Ut imperdiet dolor neque, at imperdiet lectus
              finibus in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
              Duis fringilla nisi sed magna congue ultricies. Nam faucibus lacinia auctor. Morbi eget ullamcorper erat.
              Donec auctor, nulla non pellentesque vestibulum, nisl nulla iaculis lectus, nec tincidunt elit purus eu
              leo. Phasellus quis justo consequat, commodo mi pretium, porta turpis.
            </p>
            <p class="mb-0 d-none d-md-block">
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
          </div>
        </div>
        <div class="row p-2 d-none d-md-block">
          <p>
            Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
            fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
            ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
            varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
            aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
            tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
            facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
            Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
          </p>
        </div>
      </div>

      <h3 class="h6">Esempio 2:</h3>
      <div class="affix-example container affix-parent border bg-white">
        <div class="primary-bg p-3 mb-1 text-center affix-top">
          <p class="mb-0 white-color">Affix top</p>
        </div>
        <div class="row p-5">
          <p class="h3">Orci varius natoque penatibus et magnis</p>
          <p>
            Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
            fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
            ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
            varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
            aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
            tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
            facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
            Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
          </p>
          <p class="d-none d-md-block">
            Pellentesque faucibus scelerisque diam sit amet vulputate. Aliquam vitae justo tellus. Sed pharetra, nulla
            eu ullamcorper pharetra, enim sem posuere ante, eget faucibus quam nisl vitae augue. Sed fringilla augue at
            diam facilisis consectetur. Donec ut lorem aliquet, varius nulla et, lacinia nunc. Nullam sit amet risus
            posuere, egestas nisl ac, hendrerit ex. In eu fermentum felis. Orci varius natoque penatibus et magnis dis
            parturient montes, nascetur ridiculus mus. Vivamus lacinia dictum dui, non condimentum nisi consectetur.
          </p>
        </div>
      </div>
  </section>

  <!-- Affix bottom -->
  <section>
      <h2>Affix bottom</h2>
      <h3 class="h6">Esempio 1:</h3>
      <div class="affix-example container border bg-white mb-4">
        <p>
          Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
          fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
          ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
          varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
          aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
          tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
          facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
          Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
        </p>
        <div class="row">
          <div class="col-6 col-md-3 p-2 affix-parent">
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Lorem ipsum</p>
            </div>
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Dolor sit</p>
            </div>
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Lorem ipsum</p>
            </div>
            <div class="neutral-1-bg-a7 p-3 mb-1">
              <p class="mb-0 white-color">Dolor sit</p>
            </div>
            <div class="primary-bg p-3 affix-bottom">
              <p class="mb-0 white-color">Affix bottom</p>
            </div>
          </div>
          <div class="col-6 col-md-9 p-2">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In molestie quis orci sit amet sodales. Sed
              imperdiet nisl suscipit risus pharetra, eget placerat nulla aliquam. Vestibulum ante ipsum primis in
              faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur nulla justo, ullamcorper et pharetra
              nec, sagittis id augue. Ut imperdiet dolor neque, at imperdiet lectus finibus in. Pellentesque habitant
              morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis fringilla nisi sed magna
              congue ultricies. Nam faucibus lacinia auctor. Morbi eget ullamcorper erat. Donec auctor, nulla non
              pellentesque vestibulum, nisl nulla iaculis lectus, nec tincidunt elit purus eu leo. Phasellus quis justo
              consequat, commodo mi pretium, porta turpis.
            </p>
            <p class="d-none d-md-block">
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
          </div>
        </div>
        <div class="row p-2 d-none d-md-block">
          <p>
            Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
            fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
            ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
            varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
            aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
            tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
            facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
            Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
          </p>
        </div>
      </div>

      <h3 class="h6">Esempio 2:</h3>
      <div class="affix-example container affix-parent border bg-white">
        <div class="row p-5">
          <p class="h3">Orci varius natoque penatibus et magnis</p>
          <p>
            Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
            fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
            ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
            varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
            aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
            tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
            facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
            Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
          </p>
          <p class="d-none d-md-block">
            Pellentesque faucibus scelerisque diam sit amet vulputate. Aliquam vitae justo tellus. Sed pharetra, nulla
            eu ullamcorper pharetra, enim sem posuere ante, eget faucibus quam nisl vitae augue. Sed fringilla augue at
            diam facilisis consectetur. Donec ut lorem aliquet, varius nulla et, lacinia nunc. Nullam sit amet risus
            posuere, egestas nisl ac, hendrerit ex. In eu fermentum felis. Orci varius natoque penatibus et magnis dis
            parturient montes, nascetur ridiculus mus. Vivamus lacinia dictum dui, non condimentum nisi consectetur.
          </p>
        </div>
        <div class="primary-bg p-3 mb-1 text-center affix-bottom">
          <p class="mb-0 white-color">Affix bottom</p>
        </div>
      </div>
  </section>

</div>

// examples/react-app/src/pages/Affix.jsx
import React from 'react';

const Affix = () => {
  return (
    <div class="container my-4">
      <h1>Affix</h1>

      {/* Affix top  */}
      <section>
        <h2>Affix top</h2>
        <h3 class="h6">Esempio 1:</h3>
        <div class="affix-example container border bg-white mb-4">
          <div class="row">
            <div class="col-6 col-md-3 p-2 affix-parent">
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Lorem ipsum</p>
              </div>
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Dolor sit</p>
              </div>
              <div class="primary-bg p-3 affix-top">
                <p class="mb-0 white-color">Affix top</p>
              </div>
            </div>
            <div class="col-6 col-md-9 p-2">
              <p>
                Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur nulla
                justo, ullamcorper et pharetra nec, sagittis id augue. Ut imperdiet dolor neque, at imperdiet lectus
                finibus in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
                egestas. Duis fringilla nisi sed magna congue ultricies. Nam faucibus lacinia auctor. Morbi eget
                ullamcorper erat. Donec auctor, nulla non pellentesque vestibulum, nisl nulla iaculis lectus, nec
                tincidunt elit purus eu leo. Phasellus quis justo consequat, commodo mi pretium, porta turpis.
              </p>
              <p class="mb-0 d-none d-md-block">
                Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
                semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
                fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
                Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
                Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere.
                Cras in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer
                rutrum nulla nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales
                fermentum magna volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit
                amet.
              </p>
            </div>
          </div>
          <div class="row p-2 d-none d-md-block">
            <p>
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
          </div>
        </div>

        <h3 class="h6">Esempio 2:</h3>
        <div class="affix-example container affix-parent border bg-white">
          <div class="primary-bg p-3 mb-1 text-center affix-top">
            <p class="mb-0 white-color">Affix top</p>
          </div>
          <div class="row p-5">
            <p class="h3">Orci varius natoque penatibus et magnis</p>
            <p>
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
            <p class="d-none d-md-block">
              Pellentesque faucibus scelerisque diam sit amet vulputate. Aliquam vitae justo tellus. Sed pharetra, nulla
              eu ullamcorper pharetra, enim sem posuere ante, eget faucibus quam nisl vitae augue. Sed fringilla augue
              at diam facilisis consectetur. Donec ut lorem aliquet, varius nulla et, lacinia nunc. Nullam sit amet
              risus posuere, egestas nisl ac, hendrerit ex. In eu fermentum felis. Orci varius natoque penatibus et
              magnis dis parturient montes, nascetur ridiculus mus. Vivamus lacinia dictum dui, non condimentum nisi
              consectetur.
            </p>
          </div>
        </div>
      </section>

      {/* Affix bottom  */}
      <section>
        <h2>Affix bottom</h2>
        <h3 class="h6">Esempio 1:</h3>
        <div class="affix-example container border bg-white mb-4">
          <p>
            Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed semper
            fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada fames ac
            ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at. Curabitur
            varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula. Phasellus eu
            aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras in mollis
            tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla nisi, quis
            facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna volutpat imperdiet.
            Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
          </p>
          <div class="row">
            <div class="col-6 col-md-3 p-2 affix-parent">
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Lorem ipsum</p>
              </div>
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Dolor sit</p>
              </div>
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Lorem ipsum</p>
              </div>
              <div class="neutral-1-bg-a7 p-3 mb-1">
                <p class="mb-0 white-color">Dolor sit</p>
              </div>
              <div class="primary-bg p-3 affix-bottom">
                <p class="mb-0 white-color">Affix bottom</p>
              </div>
            </div>
            <div class="col-6 col-md-9 p-2">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In molestie quis orci sit amet sodales. Sed
                imperdiet nisl suscipit risus pharetra, eget placerat nulla aliquam. Vestibulum ante ipsum primis in
                faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur nulla justo, ullamcorper et pharetra
                nec, sagittis id augue. Ut imperdiet dolor neque, at imperdiet lectus finibus in. Pellentesque habitant
                morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis fringilla nisi sed magna
                congue ultricies. Nam faucibus lacinia auctor. Morbi eget ullamcorper erat. Donec auctor, nulla non
                pellentesque vestibulum, nisl nulla iaculis lectus, nec tincidunt elit purus eu leo. Phasellus quis
                justo consequat, commodo mi pretium, porta turpis.
              </p>
              <p class="d-none d-md-block">
                Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
                semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
                fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
                Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
                Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere.
                Cras in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer
                rutrum nulla nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales
                fermentum magna volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit
                amet.
              </p>
            </div>
          </div>
          <div class="row p-2 d-none d-md-block">
            <p>
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
          </div>
        </div>

        <h3 class="h6">Esempio 2:</h3>
        <div class="affix-example container affix-parent border bg-white">
          <div class="row p-5">
            <p class="h3">Orci varius natoque penatibus et magnis</p>
            <p>
              Mauris placerat commodo tincidunt. Mauris finibus hendrerit molestie. Vestibulum gravida, lectus sed
              semper fringilla, libero felis vehicula quam, at efficitur nisl justo mattis orci. Interdum et malesuada
              fames ac ante ipsum primis in faucibus. Nulla rutrum venenatis tellus, vel suscipit tellus faucibus at.
              Curabitur varius nisi a erat vulputate aliquet. Vivamus eu purus pretium, porta lacus id, mattis ligula.
              Phasellus eu aliquam nisi. Nunc dictum in nulla eget porttitor. Mauris dapibus vitae orci id posuere. Cras
              in mollis tortor. Sed felis turpis, auctor ullamcorper ipsum vel, porta tempor felis. Integer rutrum nulla
              nisi, quis facilisis ipsum hendrerit non. Aenean at fringilla ipsum. Mauris sodales fermentum magna
              volutpat imperdiet. Nullam condimentum orci purus, eget vulputate ipsum dapibus sit amet.
            </p>
            <p class="d-none d-md-block">
              Pellentesque faucibus scelerisque diam sit amet vulputate. Aliquam vitae justo tellus. Sed pharetra, nulla
              eu ullamcorper pharetra, enim sem posuere ante, eget faucibus quam nisl vitae augue. Sed fringilla augue
              at diam facilisis consectetur. Donec ut lorem aliquet, varius nulla et, lacinia nunc. Nullam sit amet
              risus posuere, egestas nisl ac, hendrerit ex. In eu fermentum felis. Orci varius natoque penatibus et
              magnis dis parturient montes, nascetur ridiculus mus. Vivamus lacinia dictum dui, non condimentum nisi
              consectetur.
            </p>
          </div>
          <div class="primary-bg p-3 mb-1 text-center affix-bottom">
            <p class="mb-0 white-color">Affix bottom</p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Affix;
