// examples/vue-app/src/components/Button.vue
<script setup>
import { ref } from 'vue';

const clickHandler = () => {
  alert('Pulsante cliccato!');
};
</script>

<template>
  <h1>Button</h1>

  <it-button variant="primary" size="sm" type="button"> Testo del pulsante </it-button>
  <section>
    <h2>Varianti di colore</h2>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="primary" size="sm" type="button"> Primary </it-button>

        <it-button variant="primary" size="sm" :disabled="true" type="button"> Primary disabled </it-button>
      </div>

      <div class="flex">
        <it-button variant="primary" outline="{true}" size="sm" type="button"> Primary outline </it-button>

        <it-button variant="primary" outline="{true}" size="sm" :disabled="true" type="button">
          Primary outline disabled
        </it-button>
      </div>
    </div>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="secondary" size="sm" type="button"> Secondary </it-button>

        <it-button variant="secondary" size="sm" :disabled="true" type="button"> Secondary disabled </it-button>
      </div>

      <div class="flex">
        <it-button variant="secondary" outline="{true}" size="sm" type="button"> Secondary outline </it-button>

        <it-button variant="secondary" outline="{true}" size="sm" :disabled="true" type="button">
          Secondary outline disabled
        </it-button>
      </div>
    </div>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="success" size="sm" type="button"> Success </it-button>

        <it-button variant="success" size="sm" :disabled="true" type="button"> Success disabled </it-button>
      </div>

      <div class="flex">
        <it-button variant="success" outline="{true}" size="sm" type="button"> Success outline </it-button>

        <it-button variant="success" outline="{true}" size="sm" :disabled="true" type="button">
          Success outline disabled
        </it-button>
      </div>
    </div>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="danger" size="sm" type="button"> Danger </it-button>

        <it-button variant="danger" size="sm" :disabled="true" type="button"> Danger disabled </it-button>
      </div>

      <div class="flex">
        <it-button variant="danger" outline="{true}" size="sm" type="button"> Danger outline </it-button>

        <it-button variant="danger" outline="{true}" size="sm" :disabled="true" type="button">
          Danger outline disabled
        </it-button>
      </div>
    </div>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="warning" size="sm" type="button"> Warning </it-button>

        <it-button variant="warning" size="sm" :disabled="true" type="button"> Warning disabled </it-button>
      </div>

      <div class="flex">
        <it-button variant="warning" outline="{true}" size="sm" type="button"> Warning outline </it-button>

        <it-button variant="warning" outline="{true}" size="sm" :disabled="true" type="button">
          Warning outline disabled
        </it-button>
      </div>
    </div>
    <div class="flex p-0">
      <div class="flex">
        <it-button variant="link" size="sm" type="button"> Link </it-button>

        <it-button variant="link" size="sm" :disabled="true" type="button"> Link disabled </it-button>
      </div>
    </div>
  </section>
  <section>
    <h2>Varianti di dimensione</h2>
    <div class="flex">
      <it-button variant="primary" size="lg" type="button"> Primary Large </it-button>

      <it-button variant="secondary" size="lg" type="button"> Secondary Large </it-button>
    </div>
    <div class="flex">
      <it-button variant="primary" size="sm" type="button"> Primary Small </it-button>

      <it-button variant="secondary" size="sm" type="button"> Secondary Small </it-button>
    </div>
    <div class="flex">
      <it-button variant="primary" size="xs" type="button"> Primary Extra Small </it-button>

      <it-button variant="secondary" size="xs" type="button"> Secondary Extra Small </it-button>
    </div>
    <div class="flex">
      <it-button variant="primary" size="sm" block="{true}" type="button"> Primary Block </it-button>
    </div>
    <div class="flex">
      <it-button variant="secondary" size="sm" block="{true}" type="button"> Secondary Block </it-button>
    </div>
  </section>
  <section>
    <h2>Tipologie</h2>
    <div class="flex">
      <it-button variant="primary" size="sm" type="button"> Button - Testo del pulsante </it-button>

      <it-button variant="primary" size="sm" type="submit"> Submit - Testo del pulsante </it-button>

      <it-button variant="primary" size="sm" type="reset"> Reset - Testo del pulsante </it-button>
    </div>
  </section>
  <section>
    <h2>Sfondo scuro</h2>
    <div class="bg-dark p-4">
      <div class="flex p-0">
        <div class="flex">
          <it-button variant="primary" size="sm" type="button"> Primary </it-button>

          <it-button variant="primary" size="sm" :disabled="true" type="button"> Primary disabled </it-button>
        </div>

        <div class="flex">
          <it-button variant="primary" outline="{true}" size="sm" type="button"> Primary outline </it-button>

          <it-button variant="primary" outline="{true}" size="sm" :disabled="true" type="button">
            Primary outline disabled
          </it-button>
        </div>
      </div>
      <div class="flex p-0">
        <div class="flex">
          <it-button variant="secondary" size="sm" type="button"> Secondary </it-button>

          <it-button variant="secondary" size="sm" :disabled="true" type="button"> Secondary disabled </it-button>
        </div>

        <div class="flex">
          <it-button variant="secondary" outline="{true}" size="sm" type="button"> Secondary outline </it-button>

          <it-button variant="secondary" outline="{true}" size="sm" :disabled="true" type="button">
            Secondary outline disabled
          </it-button>
        </div>
      </div>
      <div class="flex p-0">
        <div class="flex">
          <it-button variant="link" size="sm" type="button"> Link </it-button>

          <it-button variant="link" size="sm" :disabled="true" type="button"> Link disabled </it-button>
        </div>
      </div>
    </div>
  </section>
  <section>
    <h2>Con icona</h2>
    <div class="flex">
      <it-button variant="success" size="lg" icon="{true}" type="button">
        <it-icon name="it-star-full" color="white" size="sm"></it-icon>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button variant="primary" icon="{true}" type="button">
        <it-icon name="it-star-full" color="white" size="sm"></it-icon>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button variant="danger" size="xs" icon="{true}" type="button">
        <it-icon name="it-star-full" color="white" size="xs"></it-icon>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button variant="link" size="xs" icon="{true}" type="button">
        <it-icon name="it-star-full" color="primary" size="xs"></it-icon>
        <span>Testo del pulsante</span>
      </it-button>
    </div>
  </section>
  <section>
    <h2>Con icona cerchiata</h2>
    <div class="flex">
      <it-button class="me-2" variant="success" size="lg" icon="{true}" type="button">
        <span class="rounded-icon">
          <it-icon name="it-user" color="success" size="xs"></it-icon>
        </span>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button class="me-2" variant="primary" icon="{true}" type="button">
        <span class="rounded-icon" size="sm">
          <it-icon name="it-user" color="primary" size="xs"></it-icon>
        </span>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button class="me-2" variant="danger" icon="{true}" type="button">
        <span class="rounded-icon">
          <it-icon name="it-user" color="danger" size="xs"></it-icon>
        </span>
        <span>Testo del pulsante</span>
      </it-button>

      <it-button class="me-2" variant="secondary" size="xs" icon="{true}" type="button">
        <span class="rounded-icon">
          <it-icon name="it-user" color="secondary" size="xs"></it-icon>
        </span>
        <span>Testo del pulsante</span>
      </it-button>
    </div>
  </section>
  <section>
    <h2>Evento di click</h2>
    <it-button variant="primary" size="sm" type="button" @click="clickHandler"> Cliccami </it-button>
  </section>
</template>

// examples/react-app/src/pages/Button.jsx
import React from 'react';

const Button = () => {
  return (
    <>
      <h1>it-button</h1>
      <it-button variant="primary" size="sm" type="button">
        Testo del pulsante
      </it-button>
      <section>
        <h2>Varianti di colore</h2>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="primary" size="sm" type="button">
              Primary
            </it-button>

            <it-button variant="primary" size="sm" disabled type="button">
              Primary disabled
            </it-button>
          </div>

          <div className="flex">
            <it-button variant="primary" outline={true} size="sm" type="button">
              Primary outline
            </it-button>

            <it-button variant="primary" outline={true} size="sm" disabled type="button">
              Primary outline disabled
            </it-button>
          </div>
        </div>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="secondary" size="sm" type="button">
              Secondary
            </it-button>

            <it-button variant="secondary" size="sm" disabled type="button">
              Secondary disabled
            </it-button>
          </div>

          <div className="flex">
            <it-button variant="secondary" outline={true} size="sm" type="button">
              Secondary outline
            </it-button>

            <it-button variant="secondary" outline={true} size="sm" disabled type="button">
              Secondary outline disabled
            </it-button>
          </div>
        </div>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="success" size="sm" type="button">
              Success
            </it-button>

            <it-button variant="success" size="sm" disabled type="button">
              Success disabled
            </it-button>
          </div>

          <div className="flex">
            <it-button variant="success" outline={true} size="sm" type="button">
              Success outline
            </it-button>

            <it-button variant="success" outline={true} size="sm" disabled type="button">
              Success outline disabled
            </it-button>
          </div>
        </div>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="danger" size="sm" type="button">
              Danger
            </it-button>

            <it-button variant="danger" size="sm" disabled type="button">
              Danger disabled
            </it-button>
          </div>

          <div className="flex">
            <it-button variant="danger" outline={true} size="sm" type="button">
              Danger outline
            </it-button>

            <it-button variant="danger" outline={true} size="sm" disabled type="button">
              Danger outline disabled
            </it-button>
          </div>
        </div>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="warning" size="sm" type="button">
              Warning
            </it-button>

            <it-button variant="warning" size="sm" disabled type="button">
              Warning disabled
            </it-button>
          </div>

          <div className="flex">
            <it-button variant="warning" outline={true} size="sm" type="button">
              Warning outline
            </it-button>

            <it-button variant="warning" outline={true} size="sm" disabled type="button">
              Warning outline disabled
            </it-button>
          </div>
        </div>
        <div className="flex p-0">
          <div className="flex">
            <it-button variant="link" size="sm" type="button">
              Link
            </it-button>

            <it-button variant="link" size="sm" disabled type="button">
              Link disabled
            </it-button>
          </div>
        </div>
      </section>
      <section>
        <h2>Varianti di dimensione </h2>
        <div className="flex">
          <it-button variant="primary" size="lg" type="button">
            Primary Large
          </it-button>

          <it-button variant="secondary" size="lg" type="button">
            Secondary Large
          </it-button>
        </div>
        <div className="flex">
          <it-button variant="primary" size="sm" type="button">
            Primary Small
          </it-button>

          <it-button variant="secondary" size="sm" type="button">
            Secondary Small
          </it-button>
        </div>
        <div className="flex">
          <it-button variant="primary" size="xs" type="button">
            Primary Extra Small
          </it-button>

          <it-button variant="secondary" size="xs" type="button">
            Secondary Extra Small
          </it-button>
        </div>
        <div className="flex">
          <it-button variant="primary" size="sm" block={true} type="button">
            Primary Block
          </it-button>
        </div>
        <div className="flex">
          <it-button variant="secondary" size="sm" block={true} type="button">
            Secondary Block
          </it-button>
        </div>
      </section>
      <section>
        <h2>Tipologie</h2>
        <div className="flex">
          <it-button variant="primary" size="sm" type="button">
            Button - Testo del pulsante
          </it-button>

          <it-button variant="primary" size="sm" type="submit">
            Submit - Testo del pulsante
          </it-button>

          <it-button variant="primary" size="sm" type="reset">
            Reset - Testo del pulsante
          </it-button>
        </div>
      </section>
      <section>
        <h2>Sfondo scuro</h2>
        <div className="bg-dark p-4">
          <div className="flex p-0">
            <div className="flex">
              <it-button variant="primary" size="sm" type="button">
                Primary
              </it-button>

              <it-button variant="primary" size="sm" disabled type="button">
                Primary disabled
              </it-button>
            </div>

            <div className="flex">
              <it-button variant="primary" outline={true} size="sm" type="button">
                Primary outline
              </it-button>

              <it-button variant="primary" outline={true} size="sm" disabled type="button">
                Primary outline disabled
              </it-button>
            </div>
          </div>
          <div className="flex p-0">
            <div className="flex">
              <it-button variant="secondary" size="sm" type="button">
                Secondary
              </it-button>

              <it-button variant="secondary" size="sm" disabled type="button">
                Secondary disabled
              </it-button>
            </div>

            <div className="flex">
              <it-button variant="secondary" outline={true} size="sm" type="button">
                Secondary outline
              </it-button>

              <it-button variant="secondary" outline={true} size="sm" disabled type="button">
                Secondary outline disabled
              </it-button>
            </div>
          </div>
          <div className="flex p-0">
            <div className="flex">
              <it-button variant="link" size="sm" type="button">
                Link
              </it-button>

              <it-button variant="link" size="sm" disabled type="button">
                Link disabled
              </it-button>
            </div>
          </div>
        </div>
      </section>
      <section>
        <h2>Con icona </h2>
        <div className="flex">
          <it-button variant="success" size="lg" icon={true} type="button">
            <it-icon name="it-star-full" color="white" size="sm"></it-icon>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button variant="primary" icon={true} type="button">
            <it-icon name="it-star-full" color="white" size="sm"></it-icon>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button variant="danger" size="xs" icon={true} type="button">
            <it-icon name="it-star-full" color="white" size="xs"></it-icon>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button variant="link" size="xs" icon={true} type="button">
            <it-icon name="it-star-full" color="primary" size="xs"></it-icon>
            <span>Testo del pulsante</span>
          </it-button>
        </div>
      </section>
      <section>
        <h2>Con icona cerchiata</h2>
        <div className="flex">
          <it-button className="me-2" variant="success" size="lg" icon={true} type="button">
            <span className="rounded-icon">
              <it-icon name="it-user" color="success" size="xs"></it-icon>
            </span>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button className="me-2" variant="primary" icon={true} type="button">
            <span className="rounded-icon" size="sm">
              <it-icon name="it-user" color="primary" size="xs"></it-icon>
            </span>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button className="me-2" variant="danger" icon={true} type="button">
            <span className="rounded-icon">
              <it-icon name="it-user" color="danger" size="xs"></it-icon>
            </span>
            <span>Testo del pulsante</span>
          </it-button>

          <it-button className="me-2" variant="secondary" size="xs" icon={true} type="button">
            <span className="rounded-icon">
              <it-icon name="it-user" color="secondary" size="xs"></it-icon>
            </span>
            <span>Testo del pulsante</span>
          </it-button>
        </div>
      </section>
      <section>
        <h2>Evento di click</h2>
        <it-button variant="primary" size="sm" type="button" onClick={() => alert('Pulsante cliccato!')}>
          Cliccami
        </it-button>
      </section>
    </>
  );
};

export default Button;
