// examples/vue-app/src/components/Callout.vue
<template>
  <h1>it-callout</h1>

  <section>
    <h2>Callout Base</h2>
    <it-callout>
      <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo callout</span>
      <p>
        Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aenean non augue non purus vestibulum varius.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Big Text</h2>
    <it-callout big-text>
      <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo callout</span>
      <p>
        Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aenean non augue non purus vestibulum varius.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Primario</h2>
    <it-callout variant="primary">
      <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
      <span slot="title">Note a riguardo</span>
      <p>
        Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque.
        Duis interdum scelerisque magna nec malesuada.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Success</h2>
    <it-callout variant="success">
      <it-icon slot="icon" name="it-check-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di conferma</span>
      <p>
        Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aenean non augue non purus vestibulum varius.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Warning</h2>
    <it-callout variant="warning">
      <it-icon slot="icon" name="it-warning-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di attenzione</span>
      <p>
        Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque.
        Duis interdum scelerisque magna nec malesuada.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Danger</h2>
    <it-callout variant="danger">
      <it-icon slot="icon" name="it-close-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di allerta</span>
      <p>
        Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque.
        Duis interdum scelerisque magna nec malesuada.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Highlight Base</h2>
    <it-callout highlight>
      <span slot="title">Titolo callout</span>
      <p>
        Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Highlight Primario</h2>
    <it-callout variant="primary" highlight>
      <span slot="title">Titolo callout</span>
      <p>
        Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Highlight Success</h2>
    <it-callout variant="success" highlight>
      <it-icon slot="icon" name="it-check-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di conferma</span>
      <p>
        Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut
        sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo
        odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla
        quis laoreet.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Highlight Warning</h2>
    <it-callout variant="warning" highlight>
      <it-icon slot="icon" name="it-warning-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di attenzione</span>
      <p>
        Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut
        sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo
        odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla
        quis laoreet.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Highlight Danger</h2>
    <it-callout variant="danger" highlight>
      <it-icon slot="icon" name="it-close-circle" aria-hidden="true"></it-icon>
      <span slot="title">Titolo di allerta</span>
      <p>
        Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut
        sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo
        odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet,
        consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla
        quis laoreet.
      </p>
    </it-callout>
  </section>

  <section>
    <h2>Callout Approfondimento</h2>
    <it-callout callout-more>
      <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
      <span slot="title">Approfondimento</span>
      <p>
        Quisque suscipit interdum augue non volutpat. Cras tristique arcu tortor. Mauris eu magna nibh. Curabitur
        malesuada neque in lectus sagittis accumsan. In vitae justo eros. Maecenas pellentesque lacinia ipsum vitae
        rhoncus. Vestibulum pretium tempor turpis, nec gravida eros viverra in. Proin dictum nibh ut semper tristique.
      </p>
      <p>
        Maecenas at erat id <strong>sem interdum efficitur eu sed nunc.</strong> Mauris sit amet erat eget augue
        molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat
        interdum magna, eu commodo odio mauris semper dolor.
      </p>
      <p>
        Maecenas vulputate ante dictum <a href="#">vestibulum volutpat</a>. Lorem ipsum dolor sit amet,
        <strong>consectetur adipiscing elit.</strong> Aenean non augue non purus vestibulum varius. Maecenas ullamcorper
        tincidunt nulla quis laoreet.
      </p>
      <it-callout-more slot="more-content">
        <span slot="label">Leggi tutto</span>
        <div slot="content">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
          est laborum
        </div>
        <a slot="extra" class="callout-more-download" href="#">
          <it-icon name="it-download" color="primary"></it-icon>
          <span class="visually-hidden">Scarica il contenuto in PDF </span>
          Download
        </a>
      </it-callout-more>
    </it-callout>
  </section>
</template>

// examples/react-app/src/pages/Callout.jsx
import React from 'react';

const Callout = () => {
  return (
    <>
      <h1>it-callout</h1>

      <section>
        <h2>Callout Base</h2>
        <it-callout>
          <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo callout</span>
          <p>
            Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aenean non augue non purus vestibulum varius.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Big Text</h2>
        <it-callout big-text>
          <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo callout</span>
          <p>
            Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aenean non augue non purus vestibulum varius.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Primario</h2>
        <it-callout variant="primary">
          <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
          <span slot="title">Note a riguardo</span>
          <p>
            Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus
            pellentesque. Duis interdum scelerisque magna nec malesuada.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Success</h2>
        <it-callout variant="success">
          <it-icon slot="icon" name="it-check-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di conferma</span>
          <p>
            Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aenean non augue non purus vestibulum varius.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Warning</h2>
        <it-callout variant="warning">
          <it-icon slot="icon" name="it-warning-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di attenzione</span>
          <p>
            Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus
            pellentesque. Duis interdum scelerisque magna nec malesuada.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Danger</h2>
        <it-callout variant="danger">
          <it-icon slot="icon" name="it-close-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di allerta</span>
          <p>
            Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus
            pellentesque. Duis interdum scelerisque magna nec malesuada.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Highlight Base</h2>
        <it-callout highlight>
          <span slot="title">Titolo callout</span>
          <p>
            Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Highlight Primario</h2>
        <it-callout variant="primary" highlight>
          <span slot="title">Titolo callout</span>
          <p>
            Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Highlight Success</h2>
        <it-callout variant="success" highlight>
          <it-icon slot="icon" name="it-check-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di conferma</span>
          <p>
            Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada
            ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu
            commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper
            tincidunt nulla quis laoreet.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Highlight Warning</h2>
        <it-callout variant="warning" highlight>
          <it-icon slot="icon" name="it-warning-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di attenzione</span>
          <p>
            Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada
            ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu
            commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper
            tincidunt nulla quis laoreet.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Highlight Danger</h2>
        <it-callout variant="danger" highlight>
          <it-icon slot="icon" name="it-close-circle" aria-hidden="true"></it-icon>
          <span slot="title">Titolo di allerta</span>
          <p>
            Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada
            ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu
            commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit
            amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper
            tincidunt nulla quis laoreet.
          </p>
        </it-callout>
      </section>

      <section>
        <h2>Callout Approfondimento</h2>
        <it-callout callout-more>
          <it-icon slot="icon" name="it-info-circle" aria-hidden="true"></it-icon>
          <span slot="title">Approfondimento</span>
          <p>
            Quisque suscipit interdum augue non volutpat. Cras tristique arcu tortor. Mauris eu magna nibh. Curabitur
            malesuada neque in lectus sagittis accumsan. In vitae justo eros. Maecenas pellentesque lacinia ipsum vitae
            rhoncus. Vestibulum pretium tempor turpis, nec gravida eros viverra in. Proin dictum nibh ut semper
            tristique.
          </p>
          <p>
            Maecenas at erat id <strong>sem interdum efficitur eu sed nunc.</strong> Mauris sit amet erat eget augue
            molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat
            interdum magna, eu commodo odio mauris semper dolor.
          </p>
          <p>
            Maecenas vulputate ante dictum <a href="#">vestibulum volutpat</a>. Lorem ipsum dolor sit amet,{' '}
            <strong>consectetur adipiscing elit.</strong> Aenean non augue non purus vestibulum varius. Maecenas
            ullamcorper tincidunt nulla quis laoreet.
          </p>
          <it-callout-more slot="more-content">
            <span slot="label">Leggi tutto</span>
            <div slot="content">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
              ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
              fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
              mollit anim id est laborum
            </div>
            <a slot="extra" className="callout-more-download" href="#">
              <it-icon name="it-download" color="primary"></it-icon>
              <span className="visually-hidden">Scarica il contenuto in PDF </span>
              Download
            </a>
          </it-callout-more>
        </it-callout>
      </section>
    </>
  );
};

export default Callout;
