// examples/svelte-app/src/pages/Callout.svelte
<h1>it-callout</h1>
<it-callout>
  <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
  <span slot="title">Titolo callout</span>
  <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
</it-callout>

<section>
  <h2>Callout Base</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout>
        <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo callout</span>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Callout Primario</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="primary">
        <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Note a riguardo</span>
        <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Callout Success</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="success">
        <it-icon slot="icon" name="it-check-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di conferma</span>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Callout Warning</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="warning">
        <it-icon slot="icon" name="it-warning-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di attenzione</span>
        <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Callout Danger</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="danger">
        <it-icon slot="icon" name="it-close-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di allerta</span>
        <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Highlight Base</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout highlight>
        <span slot="title">Titolo callout</span>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Highlight Primario</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="primary" highlight>
        <span slot="title">Titolo callout</span>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Highlight Success</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="success" highlight>
        <it-icon slot="icon" name="it-check-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di conferma</span>
        <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Highlight Warning</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="warning" highlight>
        <it-icon slot="icon" name="it-warning-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di attenzione</span>
        <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Highlight Danger</h2>
  <div class="row">
    <div class="col-12 col-lg-6">
      <it-callout variant="danger" highlight>
        <it-icon slot="icon" name="it-close-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo di allerta</span>
        <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
      </it-callout>
    </div>
  </div>
</section>

<section>
  <h2>Callout Approfondimento</h2>
  <div class="row">
    <div class="col-12">
      <it-callout more>
        <span slot="title">Approfondimento</span>
        <p>Quisque suscipit interdum augue non volutpat. Cras tristique arcu tortor. Mauris eu magna nibh. Curabitur malesuada neque in lectus sagittis accumsan. In vitae justo eros. Maecenas pellentesque lacinia ipsum vitae rhoncus. Vestibulum pretium tempor turpis, nec gravida eros viverra in. Proin dictum nibh ut semper tristique.</p>
        <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor.</p>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
        <div slot="more-content">
          <div class="collapse-header d-flex align-items-center justify-content-between">
            <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
              Leggi tutto
            </button>
            <a href="#" class="btn btn-primary ms-2">
              <it-icon name="it-download" size="xs" color="white"></it-icon>
              PDF Download
            </a>
          </div>
          <div class="collapse" id="collapseExample">
            <div class="collapse-content">
              <p>Contenuto aggiuntivo che viene mostrato quando il collapse è espanso. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
        </div>
      </it-callout>
    </div>
  </div>
</section>

// examples/react-app/src/pages/Callout.jsx
import React from 'react';

const Callout = () => {
  return (
    <>
      <h1>it-callout</h1>
      <it-callout>
        <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
        <span slot="title">Titolo callout</span>
        <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
      </it-callout>

      <section>
        <h2>Callout Base</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout>
              <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo callout</span>
              <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Callout Primario</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="primary">
              <it-icon slot="icon" name="it-info-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Note a riguardo</span>
              <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Callout Success</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="success">
              <it-icon slot="icon" name="it-check-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di conferma</span>
              <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Callout Warning</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="warning">
              <it-icon slot="icon" name="it-warning-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di attenzione</span>
              <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Callout Danger</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="danger">
              <it-icon slot="icon" name="it-close-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di allerta</span>
              <p>Quisque ex eros, pellentesque vitae enim sed, pharetra tempus dolor. Donec eu nibh ac lacus luctus pellentesque. Duis interdum scelerisque magna nec malesuada.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Highlight Base</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout highlight>
              <span slot="title">Titolo callout</span>
              <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Highlight Primario</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="primary" highlight>
              <span slot="title">Titolo callout</span>
              <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Highlight Success</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="success" highlight>
              <it-icon slot="icon" name="it-check-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di conferma</span>
              <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Highlight Warning</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="warning" highlight>
              <it-icon slot="icon" name="it-warning-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di attenzione</span>
              <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Highlight Danger</h2>
        <div className="row">
          <div className="col-12 col-lg-6">
            <it-callout variant="danger" highlight>
              <it-icon slot="icon" name="it-close-circle" size="sm" aria-hidden="true"></it-icon>
              <span slot="title">Titolo di allerta</span>
              <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor. Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
            </it-callout>
          </div>
        </div>
      </section>

      <section>
        <h2>Callout Approfondimento</h2>
        <div className="row">
          <div className="col-12">
            <it-callout more>
              <span slot="title">Approfondimento</span>
              <p>Quisque suscipit interdum augue non volutpat. Cras tristique arcu tortor. Mauris eu magna nibh. Curabitur malesuada neque in lectus sagittis accumsan. In vitae justo eros. Maecenas pellentesque lacinia ipsum vitae rhoncus. Vestibulum pretium tempor turpis, nec gravida eros viverra in. Proin dictum nibh ut semper tristique.</p>
              <p>Maecenas at erat id sem interdum efficitur eu sed nunc. Mauris sit amet erat eget augue molestie malesuada ut sed ex. In sed dignissim elit. Donec efficitur, sem eget vestibulum auctor, sem erat interdum magna, eu commodo odio mauris semper dolor.</p>
              <p>Maecenas vulputate ante dictum vestibulum volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non augue non purus vestibulum varius. Maecenas ullamcorper tincidunt nulla quis laoreet.</p>
              <div slot="more-content">
                <div className="collapse-header d-flex align-items-center justify-content-between">
                  <button className="btn btn-outline-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Leggi tutto
                  </button>
                  <a href="#" className="btn btn-primary ms-2">
                    <it-icon name="it-download" size="xs" color="white"></it-icon>
                    PDF Download
                  </a>
                </div>
                <div className="collapse" id="collapseExample">
                  <div className="collapse-content">
                    <p>Contenuto aggiuntivo che viene mostrato quando il collapse è espanso. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  </div>
                </div>
              </div>
            </it-callout>
          </div>
        </div>
      </section>
    </>
  );
};

export default Callout;
