// examples/svelte-app/src/pages/Input.svelte
<script>
  import { registerTranslation } from '@italia/dev-kit-italia/elements.js';

  const it = {
    $code: 'it',
    $name: 'Italiano',
    $dir: 'ltr',
    showHidePassword: 'Mostra/Nascondi Password (test input).',
  };

  registerTranslation(it);
</script>

<h1>it-input</h1>

<it-input id="exampleInputText" type="text" name="testo">
  <span slot="label">Campo di testo</span>
</it-input>

<it-input id="exampleInputEmail" type="email" name="email">
  <span slot="label">Campo email</span>
</it-input>

<it-input id="exampleInputNumber" type="number" name="number">
  <span slot="label">Campo numerico</span>
</it-input>

<it-input id="exampleInputNumberMinMaxStep" type="number" name="numberminmaxstep" min="10" max="100" step="10">
  <span slot="label">Campo numerico min, max, step</span>
</it-input>

<it-input id="exampleInputNumberCurrency" type="number" name="numbercurrency" value="3.50" step="0.01">
  <span slot="label">Campo numerico currency</span>
  <span slot="prepend" class="fw-semibold"> € </span>
</it-input>

<it-input id="exampleInputNumberPerc" type="number" name="numberperc" value="50">
  <span slot="label">Campo numerico percentage</span>
  <span slot="prepend" class="fw-semibold"> % </span>
</it-input>

<it-input id="exampleInputNumberAdaptive" type="number" name="numberadaptive" value="99999" adaptive>
  <span slot="label">Campo numerico adattivo</span>
</it-input>

<it-input id="exampleInputTel" type="tel" name="telefono">
  <span slot="label">Campo telefonico</span>
</it-input>

<it-input id="exampleInputTime" type="time" name="orario">
  <span slot="label">Campo orario</span>
</it-input>

<it-input id="field-disabled-example" type="text" name="field-disabled-example" disabled={true}>
  <span slot="label">Campo disabilitato</span>
</it-input>

<it-input
  id="field-readonly-example"
  type="text"
  name="field-readonly-example"
  readonly={true}
  value="Contenuto in sola lettura"
>
  <span slot="label">Campo readonly</span>
</it-input>

<it-input
  id="field-readonlyplaintext-example"
  type="text"
  name="field-readonlyplaintext-example"
  readonly={true}
  plaintext={true}
  value="Contenuto in sola lettura"
>
  <span slot="label">Campo readonly normalizzato come plaintext</span>
</it-input>

<it-input
  id="field-password-example"
  type="password"
  name="field-password-example"
  support-text="Inserisci almeno 8 caratteri e alcuni caratteri speciali."
  minlength="8"
>
  <span slot="label">Campo password</span>
</it-input>

<it-input
  id="field-password-strength-example"
  type="password"
  name="field-password-strength-example"
  support-text="Inserisci almeno 8 caratteri e alcuni caratteri speciali."
  strength-meter={true}
  minlength="8"
  suggestions={true}
>
  <span slot="label">Campo password</span>
</it-input>

<it-input id="textarea-example" type="textarea" name="textarea-example" placeholder="Testo segnaposto">
  <span slot="label">Area di testo</span>
</it-input>

<it-input id="required-example" type="text" name="required-example" required placeholder="Testo segnaposto">
  <span slot="label">Campo obbligatorio</span>
</it-input>

<it-input
  id="external-validation-example"
  type="text"
  name="external-validation-example"
  validity-message="Questo campo è obbligatorio!"
  placeholder="Testo segnaposto"
  custom-validation=""
>
  <span slot="label">Validazione esterna</span>
</it-input>

// examples/react-app/src/pages/Input.jsx
import React, { useEffect, useState } from 'react';
import { registerTranslation } from '@italia/dev-kit-italia/elements.js';

const it = {
  $code: 'it',
  $name: 'Italiano',
  $dir: 'ltr',
  showHidePassword: 'Mostra/Nascondi Password (test input).',
};

const Input = () => {
  const [translationsLoaded, setTranslationsLoaded] = useState(false);
  useEffect(() => {
    console.log('registering translation', it);
    registerTranslation(it);
    setTranslationsLoaded(true);
  }, []);

  return (
    <>
      <h1>it-input</h1>

      <it-input id="exampleInputText" type="text" name="testo">
        <span slot="label">Campo di testo</span>
      </it-input>
      <it-input id="exampleInputEmail" type="email" name="email">
        <span slot="label">Campo email</span>
      </it-input>
      <it-input id="exampleInputNumber" type="number" name="number">
        <span slot="label">Campo numerico</span>
      </it-input>
      <it-input id="exampleInputNumberMinMaxStep" type="number" name="numberminmaxstep" min="10" max="100" step="10">
        <span slot="label">Campo numerico min, max, step</span>
      </it-input>
      <it-input id="exampleInputNumberCurrency" type="number" name="numbercurrency" value="3.50" step="0.01">
        <span slot="label">Campo numerico currency</span>
        <span slot="prepend" class="fw-semibold">
          €
        </span>
      </it-input>
      <it-input id="exampleInputNumberPerc" type="number" name="numberperc" value="50">
        <span slot="label">Campo numerico percentage</span>
        <span slot="prepend" class="fw-semibold">
          %
        </span>
      </it-input>
      <it-input id="exampleInputNumberAdaptive" type="number" name="numberadaptive" value="99999" adaptive>
        <span slot="label">Campo numerico adattivo</span>
      </it-input>
      <it-input id="exampleInputTel" type="tel" name="telefono">
        <span slot="label">Campo telefonico</span>
      </it-input>
      <it-input id="exampleInputTime" type="time" name="orario">
        <span slot="label">Campo orario</span>
      </it-input>
      <it-input id="field-disabled-example" type="text" name="field-disabled-example" disabled={true}>
        <span slot="label">Campo disabilitato</span>
      </it-input>
      <it-input
        id="field-readonly-example"
        type="text"
        name="field-readonly-example"
        readonly={true}
        value="Contenuto in sola lettura"
      >
        <span slot="label">Campo readonly</span>
      </it-input>
      <it-input
        id="field-readonlyplaintext-example"
        type="text"
        name="field-readonlyplaintext-example"
        readonly={true}
        plaintext={true}
        value="Contenuto in sola lettura"
      >
        <span slot="label">Campo readonly normalizzato come plaintext</span>
      </it-input>
      {translationsLoaded && (
        <>
          <it-input
            id="field-password-example"
            type="password"
            name="field-password-example"
            support-text="Inserisci almeno 8 caratteri e alcuni caratteri speciali."
            minlength="8"
          >
            <span slot="label">Campo password</span>
          </it-input>
          <it-input
            id="field-password-strength-example"
            type="password"
            name="field-password-strength-example"
            support-text="Inserisci almeno 8 caratteri e alcuni caratteri speciali."
            strength-meter={true}
            minlength="8"
            suggestions={true}
          >
            <span slot="label">Campo password</span>
          </it-input>
        </>
      )}
      <it-input id="textarea-example" type="textarea" name="textarea-example" placeholder="Testo segnaposto">
        <span slot="label">Area di testo</span>
      </it-input>
      <it-input
        id="required-example"
        type="text"
        name="required-example"
        required={true}
        placeholder="Testo segnaposto"
      >
        <span slot="label">Campo obbligatorio</span>
      </it-input>
      <it-input
        id="external-validation-example"
        type="text"
        name="external-validation-example"
        validity-message="Questo campo è obbligatorio!"
        placeholder="Testo segnaposto"
        custom-validation={true}
      >
        <span slot="label">Validazione esterna</span>
      </it-input>
      {/* <section>
        <h2>Varianti di colore</h2>
        <div className="flex"></div>
      </section> */}
    </>
  );
};

export default Input;
