// examples/angular-app/src/app/pages/select.component.ts
/* eslint-disable class-methods-use-this */
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
  selector: 'app-select',
  standalone: true,
  templateUrl: './select.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SelectComponent {
  constructor() {}
}

<h1>it-select</h1>

 <it-select name="select-input" placeholder="Seleziona un'opzione">
  <span slot="label">Select semplice</span>
  <option value="Value 1">Opzione 1</option>
  <option value="Value 2">Opzione 2</option>
  <option value="Value 3">Opzione 3</option>
  <option value="Value 4">Opzione 4</option>
  <option value="Value 5">Opzione 5</option>
</it-select>

<it-select
  name="select-multiple"
  multiple=""
  placeholder="Seleziona una o più opzioni"
>
  <span slot="label">Select multipla</span>
  <option value="Value 1">Opzione 1</option>
  <option value="Value 2">Opzione 2</option>
  <option value="Value 3">Opzione 3</option>
  <option value="Value 4">Opzione 4</option>
  <option value="Value 5">Opzione 5</option>
</it-select>

<it-select name="select-disabled" placeholder="Seleziona un'opzione" disabled>
  <span slot="label">Select disabilitata</span>
  <option value="Value 1">Opzione 1</option>
  <option value="Value 2">Opzione 2</option>
  <option value="Value 3">Opzione 3</option>
  <option value="Value 4">Opzione 4</option>
  <option value="Value 5">Opzione 5</option>
</it-select>

<it-select name="select-group" placeholder="Seleziona un'opzione">
  <span slot="label">Select con gruppi</span>
  <optgroup label="Gruppo 1">
    <option value="1">Opzione 1</option>
    <option value="2">Opzione 2</option>
  </optgroup>
  <optgroup label="Gruppo 2">
    <option value="3">Opzione 3</option>
    <option value="4">Opzione 4</option>
  </optgroup>
</it-select>

// examples/react-app/src/pages/Select.jsx
import React from 'react';

const Select = () => {
  return (
    <>
      <h1>it-select</h1>

      <it-select name="select-input" placeholder="Seleziona un'opzione">
        <span slot="label">Select semplice</span>
        <option value="Value 1">Opzione 1</option>
        <option value="Value 2">Opzione 2</option>
        <option value="Value 3">Opzione 3</option>
        <option value="Value 4">Opzione 4</option>
        <option value="Value 5">Opzione 5</option>
      </it-select>

      <it-select name="select-multiple" multiple={true} placeholder="Seleziona una o più opzioni">
        <span slot="label">Select multipla</span>
        <option value="Value 1">Opzione 1</option>
        <option value="Value 2">Opzione 2</option>
        <option value="Value 3">Opzione 3</option>
        <option value="Value 4">Opzione 4</option>
        <option value="Value 5">Opzione 5</option>
      </it-select>

      <it-select name="select-disabled" placeholder="Seleziona un'opzione" disabled={true}>
        <span slot="label">Select disabilitata</span>
        <option value="Value 1">Opzione 1</option>
        <option value="Value 2">Opzione 2</option>
        <option value="Value 3">Opzione 3</option>
        <option value="Value 4">Opzione 4</option>
        <option value="Value 5">Opzione 5</option>
      </it-select>

      <it-select name="select-group" placeholder="Seleziona un'opzione">
        <span slot="label">Select con gruppi</span>
        <optgroup label="Gruppo 1">
          <option value="1">Opzione 1</option>
          <option value="2">Opzione 2</option>
        </optgroup>
        <optgroup label="Gruppo 2">
          <option value="3">Opzione 3</option>
          <option value="4">Opzione 4</option>
        </optgroup>
      </it-select>
    </>
  );
};

export default Select;
