// examples/vue-app/src/components/Skiplinks.vue
<script setup>
</script>

<template>
  <h1>Skiplinks</h1>

  <it-skiplinks it-aria-label="Vai a:">
    <a href="#menu">Vai al menu</a>
    <a href="#main-content">Vai al contenuto principale</a>
    <a href="#satisfaction">Questa pagina ti è stata utile?</a>
    <a href="#footer">Vai al piè di pagina</a>
    <a href="https://form.agid.gov.it/view/xyz">Dichiarazione di accessibilità (link esterno su sito AgID</a>
  </it-skiplinks>
</template>

// examples/react-app/src/pages/Skiplinks.jsx
import React from 'react';

const Skiplinks = () => {
  return (
    <>
      <h1>it-skiplinks</h1>

      <it-skiplinks it-aria-label="Vai a:">
        <a href="#menu">Vai al menu</a>
        <a href="#main-content">Vai al contenuto principale</a>
        <a href="#satisfaction">Questa pagina ti è stata utile?</a>
        <a href="#footer">Vai al piè di pagina</a>
        <a href="https://form.agid.gov.it/view/xyz">Dichiarazione di accessibilità (link esterno su sito AgID</a>
      </it-skiplinks>
    </>
  );
};

export default Skiplinks;
